import { CaseDescriptionWindowData } from './types';

type CaseSeed = Omit<CaseDescriptionWindowData, 'caseType'>;

function toKeywordSignals(includeSignals: string[], excludeSignals: string[]): string[] {
  return [...includeSignals, ...excludeSignals.map(signal => `exclude:${signal}`)];
}

function toClassificationBasis(includeSignals: string[], excludeSignals: string[]): string {
  const includeText = includeSignals.length > 0 ? includeSignals.join(', ') : '명시 키워드 없음';
  const excludeText = excludeSignals.length > 0 ? excludeSignals.join(', ') : '제외 키워드 없음';
  return `title/body/publisher 텍스트에서 포함 신호(${includeText})를 먼저 찾고, 제외 신호(${excludeText})와 충돌하지 않을 때 이 유형으로 분류한다.`;
}

function buildCase(caseType: string, seed: CaseSeed): CaseDescriptionWindowData {
  const keywordSignals = seed.keywordSignals ?? toKeywordSignals(seed.includeSignals, seed.excludeSignals);
  const classificationBasis = seed.classificationBasis ?? toClassificationBasis(seed.includeSignals, seed.excludeSignals);
  return {
    caseType,
    keywordSignals,
    classificationBasis,
    ...seed,
  };
}

function aliasCase(caseType: string, base: CaseDescriptionWindowData, overrides?: Partial<CaseSeed>): CaseDescriptionWindowData {
  return {
    ...base,
    ...overrides,
    keywordSignals: overrides?.keywordSignals ?? base.keywordSignals,
    classificationBasis: overrides?.classificationBasis ?? base.classificationBasis,
    caseType,
  };
}

const TAXONOMY_V4_CASES: Record<string, CaseDescriptionWindowData> = {
  earnings_beat_raise_positive: buildCase('earnings_beat_raise_positive', {
    caseLabelKo: '실적 호조·가이던스 상향',
    topLevel: 'long',
    description: '실적 beat, strong results, guidance raise가 직접 원인인 기사다.',
    definition: 'headline과 lead에서 분기 숫자 개선이나 가이던스 상향이 사건 본체이면 이 유형이다.',
    valuePath: '추정치 상향과 멀티플 re-rating으로 이어진다.',
    includeSignals: ['beat estimates', 'raises guidance', 'better-than-expected', 'record revenue'],
    excludeSignals: ['earnings preview', 'earnings transcript', '실적 일정 안내'],
    boundaryCase: '실적 기사 안에 다른 재료가 같이 있어도 숫자 개선이 headline 중심이면 이 유형을 우선한다.',
    quickQuestions: ['실제 결과 기사인가?', 'beat 또는 raise가 제목 핵심인가?'],
  }),
  earnings_miss_cut_negative: buildCase('earnings_miss_cut_negative', {
    caseLabelKo: '실적 부진·가이던스 하향',
    topLevel: 'short',
    description: '실적 miss, weak outlook, guidance cut이 직접 원인인 기사다.',
    definition: 'headline과 lead에서 숫자 악화 또는 가이던스 하향이 사건 본체이면 이 유형이다.',
    valuePath: '추정치 하향과 valuation compression으로 이어진다.',
    includeSignals: ['misses estimates', 'cuts guidance', 'weak outlook', 'profit warning'],
    excludeSignals: ['preview', 'transcript', '단순 컨퍼런스 발언'],
    boundaryCase: '구조조정 기사 안에 실적 언급이 섞여 있어도 중심 사건이 miss/cut이 아니면 인접 short 유형을 본다.',
    quickQuestions: ['실제 결과 기사인가?', 'miss 또는 cut이 핵심인가?'],
  }),
  earnings_preview_watch: buildCase('earnings_preview_watch', {
    caseLabelKo: '실적 발표 전 기대 기사',
    topLevel: 'residual',
    description: '실적 발표 전 expectations, watch point, preview를 설명하는 기사다.',
    definition: '아직 결과가 나오지 않았고 기대 형성 단계라면 이 유형이다.',
    valuePath: '직접 이벤트가 아니라 기대 형성 단계라 residual로 둔다.',
    includeSignals: ['ahead of earnings', 'to report q1 results', 'wall street expects'],
    excludeSignals: ['beat estimates', 'misses estimates'],
    boundaryCase: 'preview 기사라도 실제 숫자 발표 이후면 result 유형으로 보내야 한다.',
    quickQuestions: ['실제 결과 전 기사인가?', '핵심이 기대치 안내인가?'],
  }),
  earnings_transcript_snapshot: buildCase('earnings_transcript_snapshot', {
    caseLabelKo: '실적 transcript·snapshot',
    topLevel: 'residual',
    description: 'earnings call transcript, snapshot, highlights 같은 후행 정리 기사다.',
    definition: '새 사건보다 call 전사본·요약 정리 성격이 강하면 이 유형이다.',
    valuePath: '원인 기사라기보다 정리 기사라서 직접 case로 보지 않는다.',
    includeSignals: ['earnings call transcript', 'earnings snapshot', 'conference call transcript'],
    excludeSignals: ['beat estimates', 'guidance cut'],
    boundaryCase: '요약 기사 안에 방향이 보여도 실제 사건 source가 아니라면 transcript 쪽을 우선한다.',
    quickQuestions: ['전사본/스냅샷인가?', '새 사건보다 요약 정리인가?'],
  }),
  analyst_upgrade_positive: buildCase('analyst_upgrade_positive', {
    caseLabelKo: '애널리스트 상향·커버리지 개시',
    topLevel: 'long',
    description: 'buy/outperform, coverage initiation, target raise가 메인인 기사다.',
    definition: '회사 이벤트보다 sell-side formal action이 headline 중심이면 이 유형이다.',
    valuePath: '외부 해석 상향이 short-term flow와 re-rating 기대를 만든다.',
    includeSignals: ['initiates coverage', 'outperform', 'raises price target', 'buy rating'],
    excludeSignals: ['target cut', 'downgraded'],
    boundaryCase: 'analyst가 회사 이벤트를 인용해도 rating/target 변화가 headline이면 이 유형이다.',
    quickQuestions: ['formal analyst action인가?', '상향 메시지인가?'],
  }),
  analyst_downgrade_negative: buildCase('analyst_downgrade_negative', {
    caseLabelKo: '애널리스트 하향·목표가 하향',
    topLevel: 'short',
    description: 'downgrade, underperform, target cut이 메인인 기사다.',
    definition: '회사 공시보다 sell-side 하향 action이 headline 중심이면 이 유형이다.',
    valuePath: '외부 해석 악화가 기대치 조정과 수급 이탈로 이어진다.',
    includeSignals: ['downgraded', 'underperform', 'target cut', 'underweight'],
    excludeSignals: ['initiates coverage', 'raises price target'],
    boundaryCase: 'earnings miss를 인용해도 중심이 analyst action이면 이 유형을 우선한다.',
    quickQuestions: ['formal downgrade 또는 target cut인가?', '기사 주체가 analyst인가?'],
  }),
  analyst_note_amplification_positive: buildCase('analyst_note_amplification_positive', {
    caseLabelKo: '애널리스트 코멘트 증폭·긍정',
    topLevel: 'long',
    description: 'formal upgrade는 아니지만 bullish note나 single-line mention이 해설 중심인 기사다.',
    definition: '정식 rating 변경 없이 analyst mention이 가격 설명의 핵심이면 이 유형이다.',
    valuePath: '짧은 note 증폭이 short-term sentiment와 수급을 밀어 올린다.',
    includeSignals: ['analyst says', 'bofa says', 'bullish note', 'analyst comment helped'],
    excludeSignals: ['formal upgrade', 'contract award'],
    boundaryCase: '정식 rating/target 변경이 있으면 formal analyst action으로 보낸다.',
    quickQuestions: ['rating action보다 note 증폭인가?', '긍정 논지인가?'],
  }),
  analyst_note_amplification_negative: buildCase('analyst_note_amplification_negative', {
    caseLabelKo: '애널리스트 코멘트 증폭·부정',
    topLevel: 'short',
    description: 'formal downgrade는 아니지만 cautious note나 skeptical commentary가 해설 중심인 기사다.',
    definition: '정식 하향 없이 analyst warning이 가격 설명 중심이면 이 유형이다.',
    valuePath: '보수적 note가 기대치와 단기 flow를 꺾는다.',
    includeSignals: ['analyst warns', 'cautious note', 'bearish note', 'skeptical analyst'],
    excludeSignals: ['formal downgrade', 'earnings miss'],
    boundaryCase: 'target cut이나 downgrade가 있으면 formal analyst short 유형을 우선한다.',
    quickQuestions: ['정식 하향보다 note 증폭인가?', '부정 논지인가?'],
  }),
  government_contract_award_positive: buildCase('government_contract_award_positive', {
    caseLabelKo: '정부·대형 계약 수주',
    topLevel: 'long',
    description: 'prime contractor, definitive contract, government award가 직접 재료인 기사다.',
    definition: '실제 수주·backlog 확대가 headline 핵심이면 이 유형이다.',
    valuePath: '매출 가시성과 backlog 확대를 직접 시사한다.',
    includeSignals: ['contract award', 'wins contract', 'prime contractor', 'government contract'],
    excludeSignals: ['generic partnership', 'grant commentary'],
    boundaryCase: '실질 수주가 아니라 협력 관계 소개면 partnership 쪽을 검토한다.',
    quickQuestions: ['실제 수주가 headline 핵심인가?', '경제적 규모가 있는 계약인가?'],
  }),
  partnership_license_positive: buildCase('partnership_license_positive', {
    caseLabelKo: '제휴·라이선스·협업',
    topLevel: 'long',
    description: 'partnership, collaboration, licensing deal이 직접 재료인 기사다.',
    definition: '실질 협업 구조나 license agreement가 핵심이면 이 유형이다.',
    valuePath: '외부 자원 결합과 channel 확대가 가치 상승 경로를 만든다.',
    includeSignals: ['partnership', 'collaboration', 'license agreement', 'licensing deal'],
    excludeSignals: ['offering', 'lawsuit'],
    boundaryCase: 'headline에 agreement가 있어도 경제적 연결이 약하면 residual로 보낼 수 있다.',
    quickQuestions: ['경제적 제휴인가?', '실질 협업이 headline 중심인가?'],
  }),
  commercial_launch_expansion_positive: buildCase('commercial_launch_expansion_positive', {
    caseLabelKo: '출시·상업화·확장',
    topLevel: 'long',
    description: 'launch, rollout, expansion, commercialization이 직접 재료인 기사다.',
    definition: '제품/서비스 상업화 확대가 사건 본체이면 이 유형이다.',
    valuePath: '채택 확대와 매출 성장 기대를 만든다.',
    includeSignals: ['launches', 'launch', 'expands', 'commercial launch'],
    excludeSignals: ['event promotion', 'generic preview'],
    boundaryCase: '단순 제품 소개나 마케팅 copy면 residual이나 feature 쪽을 본다.',
    quickQuestions: ['실제 상업화/확장 이벤트인가?', '매출 연결이 보이는가?'],
  }),
  demand_backlog_positive: buildCase('demand_backlog_positive', {
    caseLabelKo: '수요 급증·백로그 확대',
    topLevel: 'long',
    description: 'strong demand, bookings, backlog growth가 직접 원인인 기사다.',
    definition: 'headline과 lead에서 수요·주문 가시성 확대가 핵심이면 이 유형이다.',
    valuePath: '매출 지속성과 operating leverage 기대를 높인다.',
    includeSignals: ['strong demand', 'demand surge', 'backlog', 'bookings growth'],
    excludeSignals: ['macro demand commentary', 'general feature'],
    boundaryCase: '직접 backlog 언급이 없고 peer나 섹터 read-through면 indirect 쪽을 본다.',
    quickQuestions: ['수요/백로그가 직접 언급되는가?', '회사 고유 사건인가?'],
  }),
  customer_adoption_positive: buildCase('customer_adoption_positive', {
    caseLabelKo: '고객 채택·대형 고객 확보',
    topLevel: 'long',
    description: 'major customer win, adoption, deployment 확대가 직접 재료인 기사다.',
    definition: '신규 고객 확보나 deployment가 headline 핵심이면 이 유형이다.',
    valuePath: '고객 기반 확대가 매출과 credibility 상승으로 이어진다.',
    includeSignals: ['customer win', 'adoption', 'selected by', 'deployment'],
    excludeSignals: ['generic partnership', 'watchlist article'],
    boundaryCase: '수주가 정부·방산 중심이면 contract award 쪽을 우선 검토한다.',
    quickQuestions: ['고객 채택이 headline 중심인가?', '매출 연결이 분명한가?'],
  }),
  shareholder_return_positive: buildCase('shareholder_return_positive', {
    caseLabelKo: '자사주 매입·주주환원',
    topLevel: 'long',
    description: 'share repurchase, buyback, dividend hike가 직접 재료인 기사다.',
    definition: '자본배분과 환원정책 강화가 사건 본체이면 이 유형이다.',
    valuePath: 'share count 감소와 capital return 기대가 valuation support를 만든다.',
    includeSignals: ['share repurchase', 'buyback', 'repurchase program', 'increases dividend'],
    excludeSignals: ['capital raise', 'reverse split'],
    boundaryCase: '대규모 debt-funded action이라도 headline 중심이 환원정책이면 이 유형을 유지한다.',
    quickQuestions: ['주주환원 강화가 핵심인가?', '희석이 아니라 환원인가?'],
  }),
  mna_strategic_asset_positive: buildCase('mna_strategic_asset_positive', {
    caseLabelKo: 'M&A·전략자산 거래',
    topLevel: 'long',
    description: 'acquisition, merger, buyout, strategic investment가 직접 재료인 기사다.',
    definition: '자산·회사 거래가 가치 재평가의 핵심 통로이면 이 유형이다.',
    valuePath: '전략 자산 가치 가시화와 premium 기대를 만든다.',
    includeSignals: ['acquisition', 'merger', 'buyout', 'strategic investment'],
    excludeSignals: ['distress sale', 'capital raise'],
    boundaryCase: '생존형 매각이나 채무압박 해소가 더 중심이면 distress 쪽을 본다.',
    quickQuestions: ['자산/회사 거래가 headline 핵심인가?', '전략가치 재평가가 중심인가?'],
  }),
  regulatory_clinical_positive: buildCase('regulatory_clinical_positive', {
    caseLabelKo: '승인·임상 호재',
    topLevel: 'long',
    description: 'FDA approval, positive topline, NDA/BLA acceptance가 직접 재료인 기사다.',
    definition: '핵심 자산 성공 확률 상승이 headline 중심이면 이 유형이다.',
    valuePath: '상업화 기대와 asset value re-rating을 만든다.',
    includeSignals: ['fda approval', 'positive topline', 'nda acceptance', 'pivotal data'],
    excludeSignals: ['clinical hold', 'failed endpoint'],
    boundaryCase: '결과가 mixed여도 headline이 approval/success면 positive 임상 유형을 유지한다.',
    quickQuestions: ['성공/승인이 headline 중심인가?', '핵심 자산 가치 상승을 설명하는가?'],
  }),
  regulatory_clinical_negative: buildCase('regulatory_clinical_negative', {
    caseLabelKo: '규제·임상 악재',
    topLevel: 'short',
    description: 'CRL, endpoint failure, clinical hold, rejection이 직접 재료인 기사다.',
    definition: '핵심 자산 성공 확률 하락이 headline 중심이면 이 유형이다.',
    valuePath: '상업화 지연·실패로 핵심 asset value를 깎는다.',
    includeSignals: ['complete response letter', 'clinical hold', 'failed to meet', 'fda rejection'],
    excludeSignals: ['positive topline', 'approval'],
    boundaryCase: '규제 기사라도 정책 프레임워크 일반론이면 policy read-through 쪽을 본다.',
    quickQuestions: ['실패/보류가 중심인가?', '핵심 자산 가치 하락을 설명하는가?'],
  }),
  financing_dilution_negative: buildCase('financing_dilution_negative', {
    caseLabelKo: '희석성 자금조달',
    topLevel: 'short',
    description: 'public offering, private placement, warrants, convertibles가 직접 재료인 기사다.',
    definition: '자본 조달 자체가 headline 중심이고 기존 주주 희석 우려가 분명하면 이 유형이다.',
    valuePath: '희석과 자본비용 상승 우려가 주가 하방으로 이어진다.',
    includeSignals: ['public offering', 'private placement', 'warrants', 'convertible notes'],
    excludeSignals: ['grant award', 'non-dilutive funding'],
    boundaryCase: '조달 기사라도 non-dilutive 성격이면 이 유형에 넣지 않는다.',
    quickQuestions: ['조달 자체가 headline 핵심인가?', '희석 우려가 직접적인가?'],
  }),
  capital_structure_stress_negative: buildCase('capital_structure_stress_negative', {
    caseLabelKo: '거래정지·역분할·상장유지 스트레스',
    topLevel: 'short',
    description: 'trading halt, reverse split, compliance pressure, authorized shares가 직접 재료인 기사다.',
    definition: '사업 사건보다 시장구조·상장유지 스트레스가 중심이면 이 유형이다.',
    valuePath: '유동성·희석·상장유지 우려가 주가에 직접 할인으로 반영된다.',
    includeSignals: ['trading halt', 'reverse stock split', 'minimum bid', 'authorized shares'],
    excludeSignals: ['ipo debut', 'ordinary listing'],
    boundaryCase: 'reverse split과 public offering이 같이 있으면 headline 중심 재료를 먼저 본다.',
    quickQuestions: ['사업보다 자본구조 스트레스가 중심인가?', '상장유지 이슈가 있는가?'],
  }),
  litigation_regulatory_negative: buildCase('litigation_regulatory_negative', {
    caseLabelKo: '소송·조사·회계 리스크',
    topLevel: 'short',
    description: 'lawsuit, investigation, subpoena, fraud, restatement가 직접 재료인 기사다.',
    definition: '법률·회계·신뢰 리스크가 headline 중심이면 이 유형이다.',
    valuePath: '비용 증가와 신뢰 훼손이 valuation discount를 만든다.',
    includeSignals: ['lawsuit', 'investigation', 'subpoena', 'restatement'],
    excludeSignals: ['settlement removes risk', 'approval'],
    boundaryCase: '리스크 해소·합의 완료 기사면 이 유형에 그대로 두지 않는다.',
    quickQuestions: ['조사/소송이 핵심인가?', '사업보다 법률 리스크가 중심인가?'],
  }),
  restructuring_distress_negative: buildCase('restructuring_distress_negative', {
    caseLabelKo: '구조조정·생존성 악화',
    topLevel: 'short',
    description: 'bankruptcy, going concern, layoffs, strategic alternatives가 직접 재료인 기사다.',
    definition: '성장보다 생존 모드 전환이 headline 중심이면 이 유형이다.',
    valuePath: '생존성 우려와 사업 지속성 discount를 만든다.',
    includeSignals: ['chapter 11', 'bankruptcy', 'going concern', 'layoffs'],
    excludeSignals: ['growth reorg', 'ordinary cost cuts'],
    boundaryCase: '단순 효율화 코멘트나 성장투자형 조직개편은 이 유형에 넣지 않는다.',
    quickQuestions: ['성장보다 생존이 핵심인가?', '유동성 또는 상장유지 우려가 있는가?'],
  }),
  management_governance_positive: buildCase('management_governance_positive', {
    caseLabelKo: '경영진 보강·거버넌스 개선',
    topLevel: 'long',
    description: 'experienced CEO/CFO 영입, board refresh, governance agreement가 직접 재료인 기사다.',
    definition: '운영 신뢰 회복이나 실행력 개선이 headline 중심이면 이 유형이다.',
    valuePath: '리더십 개선 기대가 valuation support를 만든다.',
    includeSignals: ['appoints new ceo', 'board refresh', 'governance agreement', 'new leadership'],
    excludeSignals: ['executive departure', 'probe'],
    boundaryCase: 'planned succession이라도 긍정 재평가가 메인 아니면 residual로 둘 수 있다.',
    quickQuestions: ['경영 보강이 긍정 이벤트인가?', '거버넌스 개선이 중심인가?'],
  }),
  management_governance_negative: buildCase('management_governance_negative', {
    caseLabelKo: '경영진 이탈·거버넌스 충격',
    topLevel: 'short',
    description: 'CEO/CFO resignation, board dispute, governance breakdown이 직접 재료인 기사다.',
    definition: '리더십 공백이나 통제 약화가 headline 중심이면 이 유형이다.',
    valuePath: '실행력 저하와 신뢰 악화 우려를 만든다.',
    includeSignals: ['ceo resigns', 'cfo resigns', 'board dispute', 'executive departs'],
    excludeSignals: ['planned succession', 'new ceo appointed'],
    boundaryCase: '새 리더 선임이 동반돼도 headline 중심이 이탈이면 negative governance를 우선한다.',
    quickQuestions: ['경영 공백/혼란이 핵심인가?', '거버넌스 충격이 headline인가?'],
  }),
  policy_regulatory_tailwind_positive: buildCase('policy_regulatory_tailwind_positive', {
    caseLabelKo: '정책·법안 수혜 read-through',
    topLevel: 'long',
    description: '법안, 정책, 규제 프레임워크 변화가 사업모델에 우호적으로 작용하는 기사다.',
    definition: '회사 직접 공시가 아니라 외부 정책 변화가 수혜 논리의 핵심이면 이 유형이다.',
    valuePath: '규제완화나 시장확대 기대가 TAM 확장 논리로 이어진다.',
    includeSignals: ['policy support', 'regulatory clarity', 'bill boosts', 'tailwind from policy'],
    excludeSignals: ['company contract', 'formal approval'],
    boundaryCase: '회사가 직접 허가를 받은 것이면 regulatory positive로 보내고, 외부 법안 수혜면 이 유형이다.',
    quickQuestions: ['직접 공시가 아니라 정책 수혜 read-through인가?', '외부 프레임 변화가 핵심인가?'],
  }),
  policy_regulatory_headwind_negative: buildCase('policy_regulatory_headwind_negative', {
    caseLabelKo: '정책·법안 역풍 read-through',
    topLevel: 'short',
    description: '법안, 규제, 정책 프레임워크 변화가 사업모델에 역풍을 주는 기사다.',
    definition: '회사 직접 악재보다 외부 정책 변화가 약세 논리의 핵심이면 이 유형이다.',
    valuePath: '규제 강화·수익경로 제한 우려가 valuation discount를 만든다.',
    includeSignals: ['bill', 'act', 'ban', 'policy risk', 'regulatory framework'],
    excludeSignals: ['fda rejection', 'lawsuit'],
    boundaryCase: '개별 회사 규제 실패가 아니라 sector-wide framework 변화일 때 이 유형을 쓴다.',
    quickQuestions: ['정책 역풍이 핵심인가?', '개별 회사 공시보다 framework 변화가 중심인가?'],
  }),
  peer_readthrough_positive: buildCase('peer_readthrough_positive', {
    caseLabelKo: 'peer 호조 read-through',
    topLevel: 'long',
    description: 'peer strong earnings, peer validation, sector leader strength가 번져오는 기사다.',
    definition: '타사 호조가 현재 ticker 재평가 논리의 중심이면 이 유형이다.',
    valuePath: 'peer 실적·수요 신호가 동종 멀티플 상승으로 번진다.',
    includeSignals: ['peer results', 'peer strength', 'sector leader', 'read-through'],
    excludeSignals: ['same company earnings', 'macro only'],
    boundaryCase: '자사 실적 기사면 direct earnings, 타사 검증이면 peer read-through로 나눈다.',
    quickQuestions: ['타사 호조가 이 종목 논리의 핵심인가?', '동종 밸류에이션 전이가 핵심인가?'],
  }),
  peer_competition_negative: buildCase('peer_competition_negative', {
    caseLabelKo: 'peer 투자·경쟁 심화 read-through',
    topLevel: 'short',
    description: 'rival launch, peer capex, substitute threat가 약세 이유인 기사다.',
    definition: '경쟁사 행동이 현재 ticker 약세 논리의 중심이면 이 유형이다.',
    valuePath: '경쟁 심화와 share loss 우려가 valuation 압박으로 이어진다.',
    includeSignals: ['rival', 'competitor', 'investment push', 'competitive pressure'],
    excludeSignals: ['same company launch', 'macro risk-off'],
    boundaryCase: '단순 sector weakness가 아니라 특정 경쟁사 행동이 보여야 이 유형을 쓴다.',
    quickQuestions: ['경쟁사 행동이 약세 이유의 중심인가?', 'share-loss 우려가 핵심인가?'],
  }),
  supply_chain_tailwind_positive: buildCase('supply_chain_tailwind_positive', {
    caseLabelKo: '공급망 완화·원가 개선 read-through',
    topLevel: 'long',
    description: 'input cost easing, supply normalization, sourcing improvement가 핵심인 기사다.',
    definition: '회사 직접 공시가 아니라 외부 공급망 개선이 긍정 논리 중심이면 이 유형이다.',
    valuePath: '원가 하락과 생산 정상화가 margin upside로 이어진다.',
    includeSignals: ['supply chain easing', 'input costs fall', 'sourcing improves', 'cost relief'],
    excludeSignals: ['company contract', 'generic macro'],
    boundaryCase: '직접 계약/고객 확보가 아니라 외부 원가 환경 개선일 때 이 유형을 쓴다.',
    quickQuestions: ['공급망 개선이 핵심 논리인가?', 'margin 개선 read-through인가?'],
  }),
  supply_chain_headwind_negative: buildCase('supply_chain_headwind_negative', {
    caseLabelKo: '공급망 차질·원가 압박 read-through',
    topLevel: 'short',
    description: 'tariff exposure, rare earth sourcing, shortage, cost inflation이 핵심인 기사다.',
    definition: '회사 직접 악재보다 외부 공급망·원가 압박이 약세 논리 중심이면 이 유형이다.',
    valuePath: '원가 상승과 생산 차질이 margin 압박으로 이어진다.',
    includeSignals: ['tariff exposure', 'rare earth', 'shortage', 'cost inflation'],
    excludeSignals: ['macro index move', 'direct lawsuit'],
    boundaryCase: '정책 법안 자체가 headline이면 policy headwind, 소재·부품 제약이면 supply-chain headwind다.',
    quickQuestions: ['공급망/원가 압박이 중심인가?', 'margin 악화 read-through인가?'],
  }),
  valuation_narrative_positive: buildCase('valuation_narrative_positive', {
    caseLabelKo: '밸류에이션 discount 해소 narrative',
    topLevel: 'long',
    description: 'undervalued, discount, rerating potential이 핵심인 기사다.',
    definition: '직접 사건보다 저평가 해소 논리가 headline 중심이면 이 유형이다.',
    valuePath: 'multiple expansion 기대가 주가 상방 논리를 만든다.',
    includeSignals: ['undervalued', 'discount', 'catch-up', 'rerating potential'],
    excludeSignals: ['best stock list', 'formal analyst upgrade'],
    boundaryCase: 'generic buy article가 아니라 valuation mispricing 논리가 중심이어야 한다.',
    quickQuestions: ['저평가 해소 narrative가 중심인가?', '직접 이벤트보다 valuation 논리가 강한가?'],
  }),
  valuation_narrative_negative: buildCase('valuation_narrative_negative', {
    caseLabelKo: '밸류에이션 부담·multiple compression narrative',
    topLevel: 'short',
    description: 'too expensive, stretched valuation, multiple compression 우려가 핵심인 기사다.',
    definition: '펀더멘털 직접 악재보다 valuation 부담 논리가 headline 중심이면 이 유형이다.',
    valuePath: '추격 매수 둔화와 de-rating 우려를 만든다.',
    includeSignals: ['too expensive', 'stretched valuation', 'multiple compression', 'overvalued'],
    excludeSignals: ['formal downgrade', 'earnings miss'],
    boundaryCase: '정식 analyst cut이 있으면 analyst short, valuation 논평만 있으면 이 유형이다.',
    quickQuestions: ['valuation 부담이 중심인가?', '직접 이벤트보다 가격이 비싸다는 논리가 중심인가?'],
  }),
  positioning_flow_positive: buildCase('positioning_flow_positive', {
    caseLabelKo: '숏커버·포지셔닝 언와인드·매수 유입',
    topLevel: 'long',
    description: 'short squeeze, fund buying, covering이 상승 이유인 기사다.',
    definition: '사업 이벤트보다 positioning과 flow가 핵심이면 이 유형이다.',
    valuePath: '기계적 수급 유입이 가격 상승을 가속한다.',
    includeSignals: ['short squeeze', 'fund buying', 'position established', 'covering'],
    excludeSignals: ['buyback', 'customer adoption'],
    boundaryCase: '내부자 매수처럼 ownership change가 기사 본체면 이 유형과 information-flow 경계를 같이 본다.',
    quickQuestions: ['사업 사건보다 flow가 핵심인가?', '수급 유입이 headline 중심인가?'],
  }),
  positioning_flow_negative: buildCase('positioning_flow_negative', {
    caseLabelKo: '차익실현·디그로싱·매도 수급',
    topLevel: 'short',
    description: 'profit-taking, de-grossing, fund selling이 하락 이유인 기사다.',
    definition: '사업 악재보다 flow unwind가 headline 중심이면 이 유형이다.',
    valuePath: '포지셔닝 축소가 단기 가격 하방을 만든다.',
    includeSignals: ['profit-taking', 'taking profits', 'de-grossing', 'fund selling'],
    excludeSignals: ['earnings miss', 'policy risk'],
    boundaryCase: 'business deterioration보다 flow unwind 설명이 중심이어야 이 유형을 쓴다.',
    quickQuestions: ['사업 악재보다 flow unwind가 중심인가?', '차익실현 설명이 headline인가?'],
  }),
  media_amplification_positive: buildCase('media_amplification_positive', {
    caseLabelKo: 'top mover·헤드라인 증폭·상승 해설',
    topLevel: 'long',
    description: 'top mover, biggest gainer, shares jumped because 같은 상승 해설 기사다.',
    definition: '이미 오른 뒤 이유를 덧붙이는 explainer 구조가 핵심이면 이 유형이다.',
    valuePath: '노출 증폭과 headline cascade가 추가 관심을 만든다.',
    includeSignals: ['top mover', 'biggest gainer', 'surging today', 'soaring today'],
    excludeSignals: ['formal upgrade', 'contract award'],
    boundaryCase: '정식 analyst action이 중심이면 analyst case, 이미 오른 뒤 해설이면 media amplification이다.',
    quickQuestions: ['이미 오른 뒤 해설 기사인가?', '노출 증폭이 핵심인가?'],
  }),
  media_amplification_negative: buildCase('media_amplification_negative', {
    caseLabelKo: 'top mover·헤드라인 증폭·하락 해설',
    topLevel: 'short',
    description: 'why stock is falling, tumbles, sell-off 같은 하락 해설 기사다.',
    definition: '이미 내린 뒤 약세 이유를 묶는 explainer 구조가 핵심이면 이 유형이다.',
    valuePath: 'headline cascade가 공포와 추가 매도를 증폭한다.',
    includeSignals: ['trading lower today', 'tumbles', 'sell-off', 'plunges'],
    excludeSignals: ['formal downgrade', 'public offering'],
    boundaryCase: '직접 하방 사건이 headline 중심이면 direct short 유형을 우선하고, 사후 해설 구조면 이 유형을 쓴다.',
    quickQuestions: ['이미 내린 뒤 해설 기사인가?', 'headline cascade가 중심인가?'],
  }),
  macro_market_commentary: buildCase('macro_market_commentary', {
    caseLabelKo: '매크로·시장 코멘터리',
    topLevel: 'residual',
    description: '금리, Fed, 인플레이션, 지수 움직임처럼 광범위한 시장 설명 기사다.',
    definition: '개별 회사 고유 사건보다 시장 전반 설명이 중심이면 이 유형이다.',
    valuePath: '외부 환경 read-through를 다루지만 개별 기업 분류력은 낮다.',
    includeSignals: ['stock market today', 'fed', 'inflation', 'nasdaq', 's&p 500'],
    excludeSignals: ['single-company event', 'peer competition'],
    boundaryCase: '특정 정책 프레임 변화가 핵심이면 policy read-through로 세분화한다.',
    quickQuestions: ['여러 종목 공통 설명인가?', '개별 회사 사건보다 시장 설명인가?'],
  }),
  market_movers_roundup: buildCase('market_movers_roundup', {
    caseLabelKo: '멀티종목 movers·watchlist 기사',
    topLevel: 'residual',
    description: '여러 종목을 묶어 radar, movers, top stocks로 나열하는 기사다.',
    definition: '개별 사건보다 스크리너·roundup 구조가 중심이면 이 유형이다.',
    valuePath: '개별 가격 원인보다 요약·큐레이션 성격이 강하다.',
    includeSignals: ['other big stocks moving', 'investors\' radars', 'most active stocks', 'top stocks'],
    excludeSignals: ['single-ticker explainer', 'direct event'],
    boundaryCase: '한 종목 집중 설명이 아니라 다종목 나열이면 이 유형으로 둔다.',
    quickQuestions: ['멀티종목 roundup인가?', '요약·레이더 기사인가?'],
  }),
  잡것들_promotional_appearance_noise: buildCase('잡것들_promotional_appearance_noise', {
    caseLabelKo: '잡것들_행사·인터뷰·홍보성 appearance',
    topLevel: 'residual',
    description: 'conference appearance, podcast, webinar, 행사 참가 안내처럼 IR 노출 중심 기사다.',
    definition: '직접 가격 영향 사건보다 행사 참가·인터뷰·패널 노출이 headline 중심이면 이 유형이다.',
    valuePath: '직접 가치 경로보다 홍보성 가시성 제공에 가까워 true residual로 둔다.',
    includeSignals: ['participate in', 'investor conference', 'podcast featuring', 'fireside chat'],
    excludeSignals: ['실적발표', '계약수주', '정책 read-through'],
    boundaryCase: '행사에서 공개한 실질 사건이 headline이면 direct/indirect case를 우선하고, 단순 appearance면 이 유형이다.',
    quickQuestions: ['행사 참가/인터뷰 공지인가?', '직접 가치 경로보다 IR 노출이 중심인가?'],
  }),
  잡것들_screener_listicle_noise: buildCase('잡것들_screener_listicle_noise', {
    caseLabelKo: '잡것들_리스트형 screener·주간 요약 노이즈',
    topLevel: 'residual',
    description: 'why these stocks, top meme stocks, penny-stock roundup처럼 다수 종목을 엮는 listicle 기사다.',
    definition: '개별 원인 분석보다 트래픽형 큐레이션·리스트 구조가 headline 중심이면 이 유형이다.',
    valuePath: '개별 가격 영향 설명보다 screener/모음집 성격이 강해 true residual로 둔다.',
    includeSignals: ['why these', 'best meme stocks', 'penny stocks', 'what you need to know'],
    excludeSignals: ['single-ticker explainer', '구체적 직접 사건'],
    boundaryCase: '한 종목 explainer가 아니라 리스트형 모음집일 때만 이 유형으로 두고, 단일 ticker 해설은 information-flow 쪽을 본다.',
    quickQuestions: ['리스트형/큐레이션 기사인가?', '개별 원인 설명보다 모음집 구조인가?'],
  }),
  ipo_listing_event: buildCase('ipo_listing_event', {
    caseLabelKo: 'IPO·상장 이벤트',
    topLevel: 'residual',
    description: 'IPO, direct listing, debut, goes public가 핵심인 기사다.',
    definition: '상장 자체가 사건 본체이면 이 유형이다.',
    valuePath: '시장 접근·유동성 이벤트지만 방향성은 case-by-case다.',
    includeSignals: ['goes public', 'ipo', 'direct listing', 'debut'],
    excludeSignals: ['trading halt', 'reverse split'],
    boundaryCase: '상장 후 reverse split이나 halt 기사면 capital-structure stress로 보낸다.',
    quickQuestions: ['상장 자체가 headline 핵심인가?', 'listing/debut 기사인가?'],
  }),
  generic_feature_commentary: buildCase('generic_feature_commentary', {
    caseLabelKo: 'feature·투자아이디어 해설',
    topLevel: 'residual',
    description: 'deep dive, buy/sell/hold, is it a buy, worth buying 같은 opinion·decision-framework 기사다.',
    definition: '직접 사건보다 opinion·해설·판단 프레임 구조가 중심이면 이 유형이다.',
    valuePath: '직접 catalyst보다 해석 레이어에 가까워 residual로 둔다.',
    includeSignals: ['is it a buy', 'worth buying', 'deep dive', 'feature', 'buy, sell, or hold', 'everyone is talking about'],
    excludeSignals: ['formal analyst action', 'earnings beat'],
    boundaryCase: 'valuation mispricing 논리가 분명하면 valuation narrative로 승격하고, 아니면 feature로 둔다.',
    quickQuestions: ['직접 사건보다 feature/opinion인가?', '새 catalyst보다 해설 비중이 큰가?'],
  }),
  // ─── V4 신규 유형 (58개) ─────────────────────────────────────
  earnings_result_mixed_neutral: buildCase('earnings_result_mixed_neutral', {
    caseLabelKo: '실적 혼재·엇갈림',
    topLevel: 'residual',
    description: 'EPS beat+매출 miss 또는 그 반대로 결과가 혼재된 기사다.',
    definition: '한 지표는 beat, 다른 지표는 miss인 경우 이 유형이다.',
    valuePath: '방향 불명확→단기 변동 후 수렴한다.',
    includeSignals: ['mixed results', 'beat eps miss revenue'],
    excludeSignals: ['clearly beat', 'clearly miss'],
    boundaryCase: 'beat/miss가 명확히 한쪽이면 해당 유형으로, 혼재 시 이 유형.',
    quickQuestions: ['beat과 miss가 동시에 언급되는가?'],
  }),
  earnings_guidance_update: buildCase('earnings_guidance_update', {
    caseLabelKo: '가이던스·전망 업데이트',
    topLevel: 'residual',
    description: 'forward guidance, outlook 수치가 핵심인 기사다. BENZINGA "Sees FY/Q" 포맷 포함.',
    definition: 'guidance 수치 업데이트가 headline 중심이면 이 유형이다.',
    valuePath: '기대치 갱신→재평가로 이어진다.',
    includeSignals: ['sees fy', 'sees q1 sales', 'outlook', 'guidance'],
    excludeSignals: ['beat', 'miss'],
    boundaryCase: 'guidance와 실적이 혼합되면 실적 유형을 우선한다.',
    quickQuestions: ['forward guidance가 핵심인가?'],
  }),
  earnings_summary_assessment: buildCase('earnings_summary_assessment', {
    caseLabelKo: '실적 요약·평가 기사',
    topLevel: 'residual',
    description: 'earnings breakdown, assessment, insights 형태의 실적 정리 기사다.',
    definition: '실적 결과를 정리·평가하는 해설 기사이면 이 유형이다.',
    valuePath: '정리·해설 성격으로 후행 정보다.',
    includeSignals: ['earnings breakdown', 'earnings assessment', 'earnings insights', 'key takeaways'],
    excludeSignals: ['guidance raise', 'guidance cut'],
    boundaryCase: 'beat/miss 프레이밍이 중심이면 해당 유형으로, 정리 중심이면 이 유형.',
    quickQuestions: ['실적 정리·해설 기사인가?'],
  }),
  earnings_call_summary: buildCase('earnings_call_summary', {
    caseLabelKo: '실적 콜 요약',
    topLevel: 'residual',
    description: 'Moby summary 등 earnings call summary 형태의 콜 요약 기사다.',
    definition: 'earnings call 내용을 간략히 정리한 기사이면 이 유형이다.',
    valuePath: '콜 요약으로 후행 정보다.',
    includeSignals: ['earnings call summary', 'moby summary'],
    excludeSignals: [],
    boundaryCase: 'transcript 전문이면 earnings_transcript_snapshot으로.',
    quickQuestions: ['콜 요약 기사인가?'],
  }),
  earnings_revenue_report_neutral: buildCase('earnings_revenue_report_neutral', {
    caseLabelKo: '실적 결과 보도(중립)',
    topLevel: 'residual',
    description: 'beat/miss 프레이밍 없이 결과를 보도하는 중립 기사다.',
    definition: '숫자만 나열하고 beat/miss 판단을 하지 않는 기사이면 이 유형이다.',
    valuePath: '사실 보도 성격.',
    includeSignals: ['reports q4', 'reports financial results', 'fourth quarter results'],
    excludeSignals: ['beat', 'miss', 'surges', 'crashes'],
    boundaryCase: '중립 보도가 아닌 beat/miss 프레이밍이 있으면 해당 유형으로.',
    quickQuestions: ['beat/miss 판단 없는 중립 보도인가?'],
  }),
  earnings_estimate_comparison: buildCase('earnings_estimate_comparison', {
    caseLabelKo: '실적 vs 추정치 비교',
    topLevel: 'residual',
    description: 'key metrics vs estimates 비교 기사다.',
    definition: '실적 지표와 추정치를 대비하는 기사이면 이 유형이다.',
    valuePath: '추정치 대비 비교 정보.',
    includeSignals: ['compared to estimates', 'key metrics', 'wall street projections'],
    excludeSignals: [],
    boundaryCase: 'beat/miss 프레이밍이 명확하면 해당 유형으로.',
    quickQuestions: ['추정치 비교 기사인가?'],
  }),
  analyst_reiteration_positive: buildCase('analyst_reiteration_positive', {
    caseLabelKo: '애널리스트 투자의견 재확인(긍정)',
    topLevel: 'long',
    description: 'Reiterates Buy/Outperform, maintains target 형태의 기존 긍정뷰 재확인 기사다.',
    definition: 'upgrade가 아닌 기존 긍정 투자의견 재확인이면 이 유형이다.',
    valuePath: '기존 긍정뷰 유지 확인→sentiment 보강.',
    includeSignals: ['reiterates buy', 'maintains buy', 'maintains price target'],
    excludeSignals: ['downgraded', 'initiates coverage'],
    boundaryCase: '새 coverage initiation은 analyst_upgrade_positive로.',
    quickQuestions: ['재확인(reiteration)인가?', '새 initiation이 아닌가?'],
  }),
  analyst_forecast_revision_positive: buildCase('analyst_forecast_revision_positive', {
    caseLabelKo: '애널리스트 전망 상향 수정',
    topLevel: 'long',
    description: 'analysts boost/increase forecasts 형태의 집합적 전망 상향 기사다.',
    definition: '복수 analyst의 전망이 집합적으로 상향된 기사이면 이 유형이다.',
    valuePath: '집합적 전망 상향→consensus 개선.',
    includeSignals: ['analysts boost', 'forecasts after upbeat'],
    excludeSignals: ['analysts cut'],
    boundaryCase: '개별 analyst upgrade는 analyst_upgrade_positive로.',
    quickQuestions: ['집합적 전망 상향인가?'],
  }),
  analyst_forecast_revision_negative: buildCase('analyst_forecast_revision_negative', {
    caseLabelKo: '애널리스트 전망 하향 수정',
    topLevel: 'short',
    description: 'analysts cut/lower forecasts 형태의 집합적 전망 하향 기사다.',
    definition: '복수 analyst의 전망이 집합적으로 하향된 기사이면 이 유형이다.',
    valuePath: '집합적 전망 하향→consensus 악화.',
    includeSignals: ['analysts cut', 'forecasts after weak'],
    excludeSignals: ['analysts boost'],
    boundaryCase: '개별 analyst downgrade는 analyst_downgrade_negative로.',
    quickQuestions: ['집합적 전망 하향인가?'],
  }),
  analyst_consensus_overview: buildCase('analyst_consensus_overview', {
    caseLabelKo: '애널리스트 컨센서스·다수의견',
    topLevel: 'residual',
    description: '다수 analyst 의견을 종합한 consensus overview 기사다.',
    definition: '특정 analyst가 아닌 다수 의견 종합이면 이 유형이다.',
    valuePath: '컨센서스 소개→정보 전달.',
    includeSignals: ['insights from analysts', 'analyst reviews', 'wall street analysts'],
    excludeSignals: ['upgrade', 'downgrade'],
    boundaryCase: '개별 analyst action이면 해당 유형으로.',
    quickQuestions: ['다수 의견 종합 기사인가?'],
  }),
  clinical_trial_initiation_positive: buildCase('clinical_trial_initiation_positive', {
    caseLabelKo: '임상시험 개시·첫 투약',
    topLevel: 'long',
    description: 'first patient dosed, trial initiated 형태의 임상 개시 이벤트 기사다.',
    definition: '새 임상시험 시작이 핵심 이벤트이면 이 유형이다.',
    valuePath: '파이프라인 진전→milestone 기대.',
    includeSignals: ['first patient dosed', 'trial initiated', 'phase initiated'],
    excludeSignals: ['trial failure'],
    boundaryCase: '임상 데이터 발표이면 clinical_trial_data_update로.',
    quickQuestions: ['임상 개시 이벤트인가?'],
  }),
  clinical_trial_data_update: buildCase('clinical_trial_data_update', {
    caseLabelKo: '임상 데이터·중간결과 업데이트',
    topLevel: 'long',
    description: 'interim data, response rate, efficacy data 형태의 임상 데이터 보고 기사다.',
    definition: '임상 데이터/결과 발표가 핵심이면 이 유형이다.',
    valuePath: '데이터 기반 자산 재평가.',
    includeSignals: ['interim data', 'response rate', 'trial data', 'efficacy data'],
    excludeSignals: ['trial initiated'],
    boundaryCase: 'FDA 절차이면 fda_procedural_action으로.',
    quickQuestions: ['임상 데이터 보고인가?'],
  }),
  drug_designation_positive: buildCase('drug_designation_positive', {
    caseLabelKo: '의약품 지정·우선심사',
    topLevel: 'long',
    description: 'QIDP, Fast Track, Breakthrough Therapy, Orphan Drug 지정 기사다.',
    definition: '규제 우선심사 지정이 핵심이면 이 유형이다.',
    valuePath: '규제 경로 단축→상업화 가속.',
    includeSignals: ['qidp designation', 'fast track', 'breakthrough therapy', 'orphan drug'],
    excludeSignals: ['fda rejection'],
    boundaryCase: 'FDA 승인이면 regulatory_clinical_positive로.',
    quickQuestions: ['우선심사 지정 이벤트인가?'],
  }),
  fda_procedural_action: buildCase('fda_procedural_action', {
    caseLabelKo: 'FDA 절차 진행·수리',
    topLevel: 'long',
    description: 'FDA accepts NDA, reverses decision, schedules review 등 FDA 절차 진행 기사다.',
    definition: 'FDA 행정 절차 진행이 핵심이면 이 유형이다.',
    valuePath: '절차 진행→approval 기대.',
    includeSignals: ['fda accepts', 'fda reverses', 'fda to review', 'pdufa date'],
    excludeSignals: ['fda rejection'],
    boundaryCase: 'FDA 최종 승인이면 regulatory_clinical_positive로.',
    quickQuestions: ['FDA 절차 진행 이벤트인가?'],
  }),
  drug_marketing_authorization: buildCase('drug_marketing_authorization', {
    caseLabelKo: '의약품 판매허가(비FDA)',
    topLevel: 'long',
    description: 'EC/EMA marketing authorization, 비FDA 지역 승인 기사다.',
    definition: 'FDA 외 지역 판매허가가 핵심이면 이 유형이다.',
    valuePath: '해외 시장 접근→매출 확대.',
    includeSignals: ['marketing authorization', 'european commission', 'conditional approval'],
    excludeSignals: [],
    boundaryCase: 'FDA 관련이면 regulatory_clinical_positive 또는 fda_procedural_action으로.',
    quickQuestions: ['비FDA 판매허가인가?'],
  }),
  acquisition_target_premium_positive: buildCase('acquisition_target_premium_positive', {
    caseLabelKo: '피인수·프리미엄 거래',
    topLevel: 'long',
    description: '회사가 프리미엄을 받고 인수되는 이벤트 기사다.',
    definition: '피인수 가격이 시장가 대비 프리미엄이면 이 유형이다.',
    valuePath: '프리미엄 실현→주주가치.',
    includeSignals: ['acquire for per share', 'tender offer', 'premium'],
    excludeSignals: [],
    boundaryCase: '일반 M&A이면 mna_strategic_asset_positive로.',
    quickQuestions: ['피인수 이벤트인가?', '프리미엄 지급?'],
  }),
  corporate_deal_billion_positive: buildCase('corporate_deal_billion_positive', {
    caseLabelKo: '대형 딜·인프라 투자',
    topLevel: 'long',
    description: 'multi-billion dollar deals, data center infrastructure 등 대형 거래 기사다.',
    definition: '수십억 달러 규모 거래/투자가 핵심이면 이 유형이다.',
    valuePath: '대형 매출·투자→가치 재평가.',
    includeSignals: ['billion deal', 'multiyear deal', 'data center', 'infrastructure'],
    excludeSignals: [],
    boundaryCase: '특정 M&A이면 mna_strategic_asset_positive로.',
    quickQuestions: ['수십억 달러 규모 거래인가?'],
  }),
  distribution_agreement_positive: buildCase('distribution_agreement_positive', {
    caseLabelKo: '유통·판매 계약',
    topLevel: 'long',
    description: '유통/판매 채널 확보 계약 기사다.',
    definition: '유통 계약 체결이 핵심이면 이 유형이다.',
    valuePath: '유통 채널 확보→매출 접근성.',
    includeSignals: ['sell drugs through', 'distribution agreement', 'sell on platform'],
    excludeSignals: [],
    boundaryCase: '일반 파트너십이면 partnership_license_positive로.',
    quickQuestions: ['유통/판매 합의인가?'],
  }),
  divestiture_exit_neutral: buildCase('divestiture_exit_neutral', {
    caseLabelKo: '사업부 매각·자산 처분',
    topLevel: 'residual',
    description: '사업부 매각, 자산 처분, 시장 철수 기사다.',
    definition: '사업부/자산을 매각하거나 시장을 떠나는 이벤트이면 이 유형이다.',
    valuePath: '포트폴리오 재편→방향 혼재.',
    includeSignals: ['divests', 'sells business', 'exits market'],
    excludeSignals: [],
    boundaryCase: '구조조정이면 restructuring_distress_negative로.',
    quickQuestions: ['사업부 매각·처분인가?'],
  }),
  product_technology_integration: buildCase('product_technology_integration', {
    caseLabelKo: '제품·기술 통합·AI 도입',
    topLevel: 'long',
    description: 'tech integration, AI adoption, platform integration 기사다.',
    definition: '기술 통합 또는 AI 도입이 핵심 이벤트이면 이 유형이다.',
    valuePath: '기술 역량 강화→경쟁력.',
    includeSignals: ['integrates with', 'adopts ai', 'ai agent', 'platform integration'],
    excludeSignals: [],
    boundaryCase: '상업화 출시이면 commercial_launch_expansion_positive로.',
    quickQuestions: ['기술 통합/AI 도입 이벤트인가?'],
  }),
  revenue_growth_milestone: buildCase('revenue_growth_milestone', {
    caseLabelKo: '매출 성장·마일스톤 달성',
    topLevel: 'long',
    description: 'record revenue, revenue growth milestone 달성 기사다.',
    definition: '매출 기록 갱신 또는 성장 마일스톤이 핵심이면 이 유형이다.',
    valuePath: '성장 증거→re-rating.',
    includeSignals: ['record revenue', 'revenue growth', 'record sales'],
    excludeSignals: [],
    boundaryCase: '실적 beat가 중심이면 earnings_beat_raise_positive로.',
    quickQuestions: ['매출 기록/마일스톤 달성인가?'],
  }),
  cost_margin_improvement: buildCase('cost_margin_improvement', {
    caseLabelKo: '원가 절감·마진 개선',
    topLevel: 'long',
    description: 'cost reduction, margin improvement, operating leverage 기사다.',
    definition: '수익성 개선이 핵심이면 이 유형이다.',
    valuePath: '수익성 개선→valuation support.',
    includeSignals: ['margin improvement', 'cost reduction', 'operating leverage'],
    excludeSignals: [],
    boundaryCase: '실적 beat와 결합되면 earnings_beat_raise_positive로.',
    quickQuestions: ['마진 개선 중심인가?'],
  }),
  dividend_special_event: buildCase('dividend_special_event', {
    caseLabelKo: '배당 개시·특별배당',
    topLevel: 'long',
    description: 'initiates dividend, special dividend 형태의 배당 이벤트 기사다.',
    definition: '배당 정책 변화가 핵심이면 이 유형이다.',
    valuePath: '배당 정책 변화→income investor 유입.',
    includeSignals: ['initiates dividend', 'special dividend', 'quarterly dividend'],
    excludeSignals: [],
    boundaryCase: '배당 인상이면 shareholder_return_positive와 겹칠 수 있다.',
    quickQuestions: ['배당 이벤트인가?'],
  }),
  insider_buying_positive: buildCase('insider_buying_positive', {
    caseLabelKo: '내부자 매수·자신감 시그널',
    topLevel: 'long',
    description: 'insider buying, director purchases 형태의 내부자 매수 기사다.',
    definition: '내부자 매수가 핵심이면 이 유형이다.',
    valuePath: '내부자 확신→신뢰 시그널.',
    includeSignals: ['insider buying', 'director purchased', 'ceo bought'],
    excludeSignals: ['insider selling'],
    boundaryCase: '내부자 매도이면 insider_selling_concern으로.',
    quickQuestions: ['내부자 매수인가?'],
  }),
  insider_selling_concern: buildCase('insider_selling_concern', {
    caseLabelKo: '내부자 매도·우려 시그널',
    topLevel: 'short',
    description: 'insider selling, executive sells shares 형태의 내부자 매도 기사다.',
    definition: '내부자 매도가 핵심이면 이 유형이다.',
    valuePath: '내부자 매도→우려 시그널.',
    includeSignals: ['insiders sell', 'insider selling', 'executive sold'],
    excludeSignals: ['insider buying'],
    boundaryCase: '내부자 매수이면 insider_buying_positive로.',
    quickQuestions: ['내부자 매도인가?'],
  }),
  institutional_stake_disclosure: buildCase('institutional_stake_disclosure', {
    caseLabelKo: '기관 지분 공시·13D/13G',
    topLevel: 'long',
    description: '13D filing, stake disclosure 형태의 기관 지분 공시 기사다.',
    definition: '기관 지분 공시(13D/13G)가 핵심이면 이 유형이다.',
    valuePath: '기관 관심→수급 기대.',
    includeSignals: ['13d disclosing', '13g', 'stake in'],
    excludeSignals: [],
    boundaryCase: '포트폴리오 변경이면 institutional_portfolio_shift로.',
    quickQuestions: ['기관 지분 공시인가?'],
  }),
  credit_facility_update: buildCase('credit_facility_update', {
    caseLabelKo: '여신 확대·부채 관리',
    topLevel: 'long',
    description: 'revolving credit expansion, credit facility 확대 기사다.',
    definition: '여신 확대 또는 부채 관리가 핵심이면 이 유형이다.',
    valuePath: '유동성 확보→재무 안정.',
    includeSignals: ['revolving credit', 'credit facility', 'extends credit'],
    excludeSignals: [],
    boundaryCase: '희석성 조달이면 financing_dilution_negative로.',
    quickQuestions: ['여신/부채 관리 이벤트인가?'],
  }),
  settlement_resolution_positive: buildCase('settlement_resolution_positive', {
    caseLabelKo: '소송 합의·분쟁 해소',
    topLevel: 'long',
    description: 'settlement, end feud, dispute resolution 형태의 분쟁 해소 기사다.',
    definition: '소송/분쟁이 해소된 이벤트이면 이 유형이다.',
    valuePath: '리스크 해소→할인 제거.',
    includeSignals: ['settlement', 'end feud', 'resolves dispute'],
    excludeSignals: ['new lawsuit'],
    boundaryCase: '새 소송이면 litigation_regulatory_negative로.',
    quickQuestions: ['분쟁 해소 이벤트인가?'],
  }),
  tariff_trade_impact: buildCase('tariff_trade_impact', {
    caseLabelKo: '관세·무역 분쟁 영향',
    topLevel: 'residual',
    description: 'tariff 부과/해제, trade war 관련 영향 기사다.',
    definition: '관세/무역 분쟁이 주가에 영향을 주는 기사이면 이 유형이다.',
    valuePath: '관세 변화→margin/수요 영향.',
    includeSignals: ['tariff', 'trade war', 'strikes down tariff'],
    excludeSignals: [],
    boundaryCase: '일반 정책이면 policy_regulatory_headwind_negative로.',
    quickQuestions: ['관세/무역 충격인가?'],
  }),
  geopolitical_market_impact: buildCase('geopolitical_market_impact', {
    caseLabelKo: '지정학·전쟁·긴장 영향',
    topLevel: 'residual',
    description: '전쟁, 지정학적 긴장, 제재 관련 기사다.',
    definition: '지정학 이벤트가 시장에 영향을 주는 기사이면 이 유형이다.',
    valuePath: '지정학 리스크→시장 변동.',
    includeSignals: ['geopolitical', 'middle east', 'iran war', 'sanctions'],
    excludeSignals: [],
    boundaryCase: '관세 관련이면 tariff_trade_impact로.',
    quickQuestions: ['지정학 이벤트인가?'],
  }),
  unusual_options_activity: buildCase('unusual_options_activity', {
    caseLabelKo: '이례적 옵션 활동',
    topLevel: 'residual',
    description: 'unusual options activity, big options bets 형태의 옵션 시장 시그널 기사다.',
    definition: '이례적 옵션 거래량/패턴이 핵심이면 이 유형이다.',
    valuePath: '옵션 시장 시그널→관심 증폭.',
    includeSignals: ['unusual options', 'options activity', 'options alert'],
    excludeSignals: [],
    boundaryCase: '공매도 관련이면 short_interest_update로.',
    quickQuestions: ['옵션 활동 기사인가?'],
  }),
  short_interest_update: buildCase('short_interest_update', {
    caseLabelKo: '공매도 비율·변동',
    topLevel: 'residual',
    description: 'short interest changes, heavily shorted 형태의 공매도 관련 기사다.',
    definition: '공매도 데이터 변동이 핵심이면 이 유형이다.',
    valuePath: '공매도 데이터→포지셔닝 힌트.',
    includeSignals: ['short interest', 'heavily shorted', 'days to cover'],
    excludeSignals: [],
    boundaryCase: 'short squeeze이면 positioning_flow_positive로.',
    quickQuestions: ['공매도 데이터 기사인가?'],
  }),
  stock_surge_explanation_positive: buildCase('stock_surge_explanation_positive', {
    caseLabelKo: '급등 해설·상승 이유',
    topLevel: 'long',
    description: '주가 급등 사유를 해설하는 기사다 (rallies X%, surges X%).',
    definition: '급등 수치와 그 원인 해설이 핵심이면 이 유형이다.',
    valuePath: '급등 해설→추가 관심 유발.',
    includeSignals: ['rallies over', 'surges', 'soars', 'jumps %'],
    excludeSignals: ['crashes', 'plunges'],
    boundaryCase: '단순 "trading higher"이면 media_amplification_positive로.',
    quickQuestions: ['급등 사유 해설인가?', '구체적 %가 있는가?'],
  }),
  stock_crash_explanation_negative: buildCase('stock_crash_explanation_negative', {
    caseLabelKo: '급락 해설·하락 이유',
    topLevel: 'short',
    description: '주가 급락 사유를 해설하는 기사다 (nosedives, crashes X%).',
    definition: '급락 수치와 그 원인 해설이 핵심이면 이 유형이다.',
    valuePath: '급락 해설→공포 증폭.',
    includeSignals: ['nosedives', 'crashes', 'stock falls %', 'tanks'],
    excludeSignals: ['surges', 'rallies'],
    boundaryCase: '단순 "trading lower"이면 media_amplification_negative로.',
    quickQuestions: ['급락 사유 해설인가?', '구체적 %가 있는가?'],
  }),
  circuit_breaker_halt_event: buildCase('circuit_breaker_halt_event', {
    caseLabelKo: '서킷브레이커·일시정지',
    topLevel: 'residual',
    description: 'circuit breaker halt, trading halted 형태의 거래 일시정지 이벤트 기사다.',
    definition: '서킷브레이커 또는 거래 일시정지가 핵심이면 이 유형이다.',
    valuePath: '급변 이벤트→변동성.',
    includeSignals: ['circuit breaker', 'halted on', 'shares halted'],
    excludeSignals: [],
    boundaryCase: '일반 급등/급락이면 해당 유형으로.',
    quickQuestions: ['서킷브레이커 이벤트인가?'],
  }),
  technical_analysis_signal: buildCase('technical_analysis_signal', {
    caseLabelKo: '기술적 분석·차트 시그널',
    topLevel: 'residual',
    description: 'golden cross, moving average, technical pattern 기사다.',
    definition: '기술적 분석 시그널이 핵심이면 이 유형이다.',
    valuePath: '기술적 신호→트레이더 관심.',
    includeSignals: ['golden cross', '200-day', 'moving average', 'trend barrier'],
    excludeSignals: [],
    boundaryCase: '가격 움직임 해설이면 media_amplification으로.',
    quickQuestions: ['기술적 분석 기사인가?'],
  }),
  stock_why_moving_explanation: buildCase('stock_why_moving_explanation', {
    caseLabelKo: '주가 움직임 이유·해설',
    topLevel: 'residual',
    description: '"What\'s going on with X stock" 형태의 주가 움직임 이유 해설 기사다.',
    definition: '주가 움직임의 이유를 설명하는 기사이면 이 유형이다.',
    valuePath: '이유 해설→정보 전달.',
    includeSignals: ["what's going on with", "here's why", "what's behind"],
    excludeSignals: [],
    boundaryCase: '구체적 이유(실적, 계약 등)가 명확하면 해당 유형으로.',
    quickQuestions: ['주가 움직임 이유 해설인가?'],
  }),
  investment_thesis_article: buildCase('investment_thesis_article', {
    caseLabelKo: '투자 논점·알파 아이디어',
    topLevel: 'residual',
    description: '"should you buy", "is it a buy", bull/bear case 형태의 투자 논점 기사다.',
    definition: '투자 판단/논점이 핵심이면 이 유형이다.',
    valuePath: 'opinion/thesis→정보 전달.',
    includeSignals: ['should you buy', 'is it a buy', 'worth buying', 'bull case', 'bear case'],
    excludeSignals: [],
    boundaryCase: 'valuation 논리가 분명하면 valuation narrative로.',
    quickQuestions: ['투자 논점/판단 기사인가?'],
  }),
  sector_movers_session_roundup: buildCase('sector_movers_session_roundup', {
    caseLabelKo: '섹터별 장중 movers 기사',
    topLevel: 'residual',
    description: '"12 Health Care Stocks Moving In Monday\'s Pre-Market Session" 형태의 섹터별 movers 기사다.',
    definition: '특정 섹터의 장중·프리마켓 movers를 나열하는 기사이면 이 유형이다.',
    valuePath: '섹터 movers 목록→스크리너 성격.',
    includeSignals: ['stocks moving in session', 'stocks moving in pre-market'],
    excludeSignals: [],
    boundaryCase: '특정 종목 중심이면 해당 유형으로.',
    quickQuestions: ['섹터 movers 리스트인가?'],
  }),
  daily_market_index_summary: buildCase('daily_market_index_summary', {
    caseLabelKo: '일간 지수·시장 요약',
    topLevel: 'residual',
    description: '"Dow Gains/Dips X Points" 형태의 일간 시장 요약 기사다.',
    definition: '지수 일간 움직임 요약이 핵심이면 이 유형이다.',
    valuePath: '시장 요약→배경 정보.',
    includeSignals: ['dow dips', 'dow gains', 'nasdaq gains over', 'us stocks mixed'],
    excludeSignals: [],
    boundaryCase: '광범위한 매크로이면 macro_market_commentary로.',
    quickQuestions: ['일간 지수 요약인가?'],
  }),
  market_moving_news_digest: buildCase('market_moving_news_digest', {
    caseLabelKo: '시장 영향 뉴스 다이제스트',
    topLevel: 'residual',
    description: '"Market-Moving News for [Date]" 형태의 뉴스 다이제스트 기사다.',
    definition: '일별 시장 영향 뉴스를 모은 다이제스트이면 이 유형이다.',
    valuePath: '뉴스 다이제스트→종합 요약.',
    includeSignals: ['market-moving news for', 'market moving news'],
    excludeSignals: [],
    boundaryCase: '개별 종목 뉴스이면 해당 유형으로.',
    quickQuestions: ['시장 뉴스 다이제스트인가?'],
  }),
  trending_stocks_chatter: buildCase('trending_stocks_chatter', {
    caseLabelKo: '인기종목·시장 잡담',
    topLevel: 'residual',
    description: 'trending tickers, market chatter, stocks to watch 형태의 기사다.',
    definition: '인기종목·시장 잡담이 핵심이면 이 유형이다.',
    valuePath: '트렌딩 소개→관심 환기.',
    includeSignals: ['trending tickers', 'market chatter', 'stocks to watch'],
    excludeSignals: [],
    boundaryCase: '멀티종목 나열이면 market_movers_roundup으로.',
    quickQuestions: ['인기종목/시장 잡담인가?'],
  }),
  sector_update_commentary: buildCase('sector_update_commentary', {
    caseLabelKo: '섹터 업데이트·코멘터리',
    topLevel: 'residual',
    description: '"Sector Update: Health Care Stocks" 형태의 섹터 코멘터리 기사다.',
    definition: '섹터 업데이트가 핵심이면 이 유형이다.',
    valuePath: '섹터 업데이트→배경 정보.',
    includeSignals: ['sector update', 'financial stocks decline', 'health care stocks'],
    excludeSignals: [],
    boundaryCase: '광범위 시장이면 macro_market_commentary로.',
    quickQuestions: ['섹터 업데이트인가?'],
  }),
  gapping_stocks_analysis: buildCase('gapping_stocks_analysis', {
    caseLabelKo: '갭 상승/하락 종목',
    topLevel: 'residual',
    description: 'gapping stocks, gap-ups/gap-downs 형태의 갭 종목 분석 기사다.',
    definition: '갭 종목 분석이 핵심이면 이 유형이다.',
    valuePath: '갭 분석→트레이딩 관심.',
    includeSignals: ['gapping stocks', 'gap up', 'gap down'],
    excludeSignals: [],
    boundaryCase: '프리마켓 movers이면 premarket_afterhours_movers로.',
    quickQuestions: ['갭 종목 분석인가?'],
  }),
  premarket_afterhours_movers: buildCase('premarket_afterhours_movers', {
    caseLabelKo: '프리마켓·애프터마켓 movers',
    topLevel: 'residual',
    description: 'pre-market/after-hours movers 형태의 장전·장후 움직임 기사다.',
    definition: '장전/장후 movers 나열이 핵심이면 이 유형이다.',
    valuePath: '장전/장후 movers→트레이딩 관심.',
    includeSignals: ['pre-market session', 'after-market session', 'before the opening bell'],
    excludeSignals: [],
    boundaryCase: '섹터별이면 sector_movers_session_roundup으로.',
    quickQuestions: ['장전/장후 movers인가?'],
  }),
  oil_energy_commodity_impact: buildCase('oil_energy_commodity_impact', {
    caseLabelKo: '유가·에너지·원자재 영향',
    topLevel: 'residual',
    description: 'oil price, commodity price 움직임 영향 기사다.',
    definition: '원자재 가격 변동이 핵심이면 이 유형이다.',
    valuePath: '원자재 가격 영향→관련주 영향.',
    includeSignals: ['oil tops', 'oil jumps', 'crude oil', 'commodity'],
    excludeSignals: [],
    boundaryCase: '광범위 매크로이면 macro_market_commentary로.',
    quickQuestions: ['원자재 가격 충격인가?'],
  }),
  mining_resource_update: buildCase('mining_resource_update', {
    caseLabelKo: '광산·자원 업데이트',
    topLevel: 'long',
    description: 'mineral resource estimate, drill program 형태의 광업 자원 업데이트 기사다.',
    definition: '광물 자원 업데이트가 핵심이면 이 유형이다.',
    valuePath: '자원 가치 상향→재평가.',
    includeSignals: ['mineral resource', 'drill program', 'resource estimate'],
    excludeSignals: [],
    boundaryCase: '에너지 가격이면 oil_energy_commodity_impact로.',
    quickQuestions: ['광물 자원 업데이트인가?'],
  }),
  crypto_digital_asset_event: buildCase('crypto_digital_asset_event', {
    caseLabelKo: '암호화폐·디지털자산 이벤트',
    topLevel: 'residual',
    description: 'crypto, stablecoin, blockchain 관련 이벤트 기사다.',
    definition: '암호화폐/디지털자산이 핵심이면 이 유형이다.',
    valuePath: '디지털자산 이벤트→재평가.',
    includeSignals: ['bitcoin', 'stablecoin', 'cryptocurrency', 'blockchain'],
    excludeSignals: [],
    boundaryCase: '일반 fintech이면 product_technology_integration으로.',
    quickQuestions: ['암호화폐 이벤트인가?'],
  }),
  renewable_energy_milestone: buildCase('renewable_energy_milestone', {
    caseLabelKo: '신재생에너지 마일스톤',
    topLevel: 'long',
    description: 'solar project, renewable energy, clean energy 마일스톤 기사다.',
    definition: '신재생에너지 프로젝트/마일스톤이 핵심이면 이 유형이다.',
    valuePath: '에너지전환 투자→성장.',
    includeSignals: ['solar', 'renewable energy', 'clean energy', 'wind farm'],
    excludeSignals: [],
    boundaryCase: '원유 영향이면 oil_energy_commodity_impact로.',
    quickQuestions: ['신재생에너지 이벤트인가?'],
  }),
  biotech_pipeline_presentation: buildCase('biotech_pipeline_presentation', {
    caseLabelKo: '바이오 파이프라인·학회 발표',
    topLevel: 'residual',
    description: 'data presentation at medical conference 형태의 학회 발표 기사다.',
    definition: '학회 데이터 발표 예정이 핵심이면 이 유형이다.',
    valuePath: '학회 발표→관심.',
    includeSignals: ['present data at', 'present at meeting', 'upcoming presentation'],
    excludeSignals: [],
    boundaryCase: '실제 데이터이면 clinical_trial_data_update로.',
    quickQuestions: ['학회 발표 예정인가?'],
  }),
  잡것들_company_event_schedule_noise: buildCase('잡것들_company_event_schedule_noise', {
    caseLabelKo: '잡것들_이벤트 일정·스케줄 공지',
    topLevel: 'residual',
    description: 'events schedule, webcast schedule 형태의 일정 공지 기사다.',
    definition: '이벤트 일정 공지가 핵심이면 이 유형이다.',
    valuePath: '일정 안내→저정보.',
    includeSignals: ['events schedule', 'schedules webcast', 'sets schedule'],
    excludeSignals: [],
    boundaryCase: '실적 발표 preview이면 earnings_preview_watch로.',
    quickQuestions: ['일정 공지인가?'],
  }),
  잡것들_company_award_recognition: buildCase('잡것들_company_award_recognition', {
    caseLabelKo: '잡것들_수상·인증·랭킹',
    topLevel: 'residual',
    description: 'award, ranking, named one of 형태의 인지도 이벤트 기사다.',
    definition: '수상/랭킹이 핵심이면 이 유형이다.',
    valuePath: '인지도 이벤트→저영향.',
    includeSignals: ['named one of', 'award', 'ranked'],
    excludeSignals: [],
    boundaryCase: 'feature 기사이면 generic_feature_commentary로.',
    quickQuestions: ['수상/랭킹 기사인가?'],
  }),
  patent_ip_event: buildCase('patent_ip_event', {
    caseLabelKo: '특허·IP 이벤트',
    topLevel: 'residual',
    description: 'patent win/loss, IP acquisition 형태의 특허 이벤트 기사다.',
    definition: '특허/IP 이벤트가 핵심이면 이 유형이다.',
    valuePath: 'IP 가치 변화.',
    includeSignals: ['patent', 'intellectual property'],
    excludeSignals: [],
    boundaryCase: '소송이면 litigation_regulatory_negative로.',
    quickQuestions: ['특허/IP 이벤트인가?'],
  }),
  activist_investor_event: buildCase('activist_investor_event', {
    caseLabelKo: '행동주의 투자자 이벤트',
    topLevel: 'long',
    description: 'activist investor, proxy fight, board fight 형태의 행동주의 이벤트 기사다.',
    definition: '행동주의 투자자 개입이 핵심이면 이 유형이다.',
    valuePath: '거버넌스 변화→재평가.',
    includeSignals: ['activist', 'board fight', 'proxy fight'],
    excludeSignals: [],
    boundaryCase: '일반 지분 공시이면 institutional_stake_disclosure로.',
    quickQuestions: ['행동주의 투자자 개입인가?'],
  }),
  institutional_portfolio_shift: buildCase('institutional_portfolio_shift', {
    caseLabelKo: '기관 포트폴리오 변경(13F)',
    topLevel: 'residual',
    description: 'fund adds/exits, portfolio shift, 13F filing 형태의 기관 포트폴리오 변경 기사다.',
    definition: '기관 포트폴리오 변경이 핵심이면 이 유형이다.',
    valuePath: '기관 수급 변화.',
    includeSignals: ['portfolio shift', 'adds position', 'exits position', '13f'],
    excludeSignals: [],
    boundaryCase: '활동적 지분 공시이면 institutional_stake_disclosure로.',
    quickQuestions: ['기관 포트폴리오 변경인가?'],
  }),
  stock_comparison_article: buildCase('stock_comparison_article', {
    caseLabelKo: '종목 비교·vs 기사',
    topLevel: 'residual',
    description: '"A vs B: which stock is better" 형태의 종목 비교 기사다.',
    definition: '두 종목을 직접 비교하는 기사이면 이 유형이다.',
    valuePath: '비교 분석→투자 판단 보조.',
    includeSignals: ['which stock is', 'better value option', 'vs which is the better'],
    excludeSignals: [],
    boundaryCase: '투자 논점이면 investment_thesis_article로.',
    quickQuestions: ['종목 간 비교 기사인가?'],
  }),
  debt_restructuring_event: buildCase('debt_restructuring_event', {
    caseLabelKo: '부채 관리·리파이낸싱',
    topLevel: 'long',
    description: 'debt paydown, refinancing, maturity extension 형태의 부채 관리 기사다.',
    definition: '부채 관리/리파이낸싱이 핵심이면 이 유형이다.',
    valuePath: '재무 건전성→안정.',
    includeSignals: ['refinancing', 'debt paydown', 'maturity extension', 'deleveraging'],
    excludeSignals: [],
    boundaryCase: '여신 확대이면 credit_facility_update로.',
    quickQuestions: ['부채 관리 이벤트인가?'],
  }),
  pre_market_gap_move: buildCase('pre_market_gap_move', {
    caseLabelKo: '프리마켓 갭 무브',
    topLevel: 'residual',
    description: '프리마켓에서 갭 상승/하락 후 해설하는 기사다.',
    definition: '프리마켓 갭 움직임이 핵심이면 이 유형이다.',
    valuePath: '갭 해설→트레이딩 관심.',
    includeSignals: ['gaps up', 'gaps down', 'pre-market gap'],
    excludeSignals: [],
    boundaryCase: '갭 종목 나열이면 gapping_stocks_analysis로.',
    quickQuestions: ['프리마켓 갭 해설인가?'],
  }),
  unknown: buildCase('unknown', {
    caseLabelKo: 'unknown',
    topLevel: 'residual',
    description: '현재 taxonomy 어디에도 안정적으로 들어가지 않는 미분류 기사다.',
    definition: '명백한 잡것들_ 노이즈도 아니고, 기존 case 규칙에도 안 맞으면 이 유형이다.',
    valuePath: '다음 tranche에서 별도 case로 승격될 수 있다.',
    includeSignals: ['substantive but unmatched', 'uncaptured pattern'],
    excludeSignals: ['잡것들_ prefix 노이즈 기사', '기존 명확한 case'],
    boundaryCase: '노이즈성 기사면 잡것들_ 계열로, 실제 사건성은 있는데 rule이 없으면 unknown으로 둔다.',
    quickQuestions: ['현재 rule로 안정 분류가 안 되는가?', '새 case 후보인가?'],
  }),
  meaningless_others: buildCase('meaningless_others', {
    caseLabelKo: '잡것들(legacy)',
    topLevel: 'residual',
    description: 'legacy broad fallback이다. 새 run에서는 잡것들_ 계열과 unknown으로 분리한다.',
    definition: '이전 run 호환용 broad fallback bucket이다.',
    valuePath: 'legacy fallback.',
    includeSignals: ['legacy fallback'],
    excludeSignals: ['unknown', '잡것들_*'],
    boundaryCase: '새 taxonomy에서는 이 broad fallback을 줄이는 것이 목표다.',
    quickQuestions: ['legacy run row인가?'],
  }),
};

const LEGACY_COMPAT_CASES: Record<string, CaseDescriptionWindowData> = {
  promotional_appearance_noise: aliasCase('promotional_appearance_noise', TAXONOMY_V4_CASES.잡것들_promotional_appearance_noise, {
    caseLabelKo: '행사·인터뷰·홍보성 appearance',
    description: 'legacy key다. 새 taxonomy에서는 잡것들_promotional_appearance_noise로 본다.',
  }),
  screener_listicle_noise: aliasCase('screener_listicle_noise', TAXONOMY_V4_CASES.잡것들_screener_listicle_noise, {
    caseLabelKo: '리스트형 screener·주간 요약 노이즈',
    description: 'legacy key다. 새 taxonomy에서는 잡것들_screener_listicle_noise로 본다.',
  }),
  company_event_schedule_noise: aliasCase('company_event_schedule_noise', TAXONOMY_V4_CASES.잡것들_company_event_schedule_noise, {
    caseLabelKo: '이벤트 일정·스케줄 공지',
    description: 'legacy key다. 새 taxonomy에서는 잡것들_company_event_schedule_noise로 본다.',
  }),
  company_award_recognition: aliasCase('company_award_recognition', TAXONOMY_V4_CASES.잡것들_company_award_recognition, {
    caseLabelKo: '수상·인증·랭킹',
    description: 'legacy key다. 새 taxonomy에서는 잡것들_company_award_recognition으로 본다.',
  }),
  earnings_guidance_positive: aliasCase('earnings_guidance_positive', TAXONOMY_V4_CASES.earnings_beat_raise_positive, {
    caseLabelKo: '실적 호조·가이던스 상향',
    description: 'legacy broad bucket이다. taxonomy v3에서는 earnings_beat_raise_positive로 세분화했다.',
  }),
  earnings_guidance_negative: aliasCase('earnings_guidance_negative', TAXONOMY_V4_CASES.earnings_miss_cut_negative, {
    caseLabelKo: '실적 부진·가이던스 하향',
    description: 'legacy broad bucket이다. taxonomy v3에서는 earnings_miss_cut_negative로 세분화했다.',
  }),
  contract_partnership_positive: buildCase('contract_partnership_positive', {
    caseLabelKo: '대형 계약·제휴·수주',
    topLevel: 'long',
    description: 'legacy broad bucket이다. taxonomy v3에서는 정부 계약과 partnership/license를 분리했다.',
    definition: '예전 run에서 계약 수주와 협업 기사 전반을 묶어 두던 상위 유형이다.',
    valuePath: '매출 가시성 또는 전략적 외부 자원 유입 기대를 만든다.',
    includeSignals: ['contract award', 'wins contract', 'partnership', 'collaboration'],
    excludeSignals: ['형식적 MOU', 'offering', 'lawsuit'],
    boundaryCase: '새 run에서는 government_contract_award_positive와 partnership_license_positive로 나눠서 본다.',
    quickQuestions: ['old run broad bucket인가?', '새 run에서는 더 세분화됐는가?'],
  }),
  product_growth_positive: aliasCase('product_growth_positive', TAXONOMY_V4_CASES.commercial_launch_expansion_positive, {
    caseLabelKo: '제품·서비스 성장 기대',
    description: 'legacy broad bucket이다. taxonomy v3에서는 launch/expansion, demand/backlog, customer adoption을 분리했다.',
  }),
  mna_asset_value_positive: aliasCase('mna_asset_value_positive', TAXONOMY_V4_CASES.mna_strategic_asset_positive, {
    caseLabelKo: 'M&A·전략가치 재평가',
    description: 'legacy broad bucket이다. taxonomy v3에서는 mna_strategic_asset_positive로 반영했다.',
  }),
  macro_sector_readthrough: buildCase('macro_sector_readthrough', {
    caseLabelKo: '매크로·섹터 read-through',
    topLevel: 'residual',
    description: 'legacy broad residual bucket이다. taxonomy v3에서는 policy, peer, supply-chain, valuation, media, macro commentary를 분리했다.',
    definition: '예전 run에서 외부 환경·해설 기사를 넓게 묶어 두던 상위 유형이다.',
    valuePath: '외부 환경 변화가 개별 종목에 read-through된다는 점은 맞지만, 분류력이 너무 넓었다.',
    includeSignals: ['tariff', 'fed', 'inflation', 'sector weakness', 'why stock moved'],
    excludeSignals: ['직접 실적/계약/임상 기사'],
    boundaryCase: '새 run에서는 policy_regulatory, peer, supply_chain, media_amplification, macro_market_commentary 등으로 나눠 읽어야 한다.',
    quickQuestions: ['old broad residual bucket인가?', '새 taxonomy에서는 더 구체적인 원인으로 나눌 수 있는가?'],
  }),
};

export const MODEL2_CASE_DESCRIPTIONS: Record<string, CaseDescriptionWindowData> = {
  ...TAXONOMY_V4_CASES,
  ...LEGACY_COMPAT_CASES,
};

export function getModel2CaseDescription(caseType: string): CaseDescriptionWindowData {
  return MODEL2_CASE_DESCRIPTIONS[caseType] ?? MODEL2_CASE_DESCRIPTIONS.unknown;
}