import { CaseDescriptionWindowData } from './types';

export const MODEL2_CASE_DESCRIPTIONS: Record<string, CaseDescriptionWindowData> = {
  earnings_guidance_positive: {
    caseType: 'earnings_guidance_positive',
    caseLabelKo: '실적 호조·가이던스 상향',
    topLevel: 'long',
    description: '실적 beat, 수익성 개선, 가이던스 상향처럼 펀더멘털 상방을 직접 시사하는 기사다.',
    definition: 'headline/lead에서 earnings beat 또는 guidance raise가 핵심 사건인 경우 이 유형으로 분류한다.',
    valuePath: '숫자 개선 -> 추정치 상향 -> 밸류에이션 재평가 경로를 가진다.',
    includeSignals: ['beat estimates', 'beats estimates', 'raises guidance', 'record revenue', 'strong outlook', 'better-than-expected'],
    excludeSignals: ['단순 실적 일정 안내', 'earnings transcript만 있고 방향성이 약한 경우', '실적 기사지만 miss 또는 weak outlook가 핵심인 경우'],
    boundaryCase: '실적 기사 안에 계약/신제품 언급이 같이 있어도 숫자 개선이 메인 메시지면 이 유형을 유지한다.',
    quickQuestions: ['headline의 핵심이 beat 또는 raise인가?', '본문 첫 문단만 읽어도 숫자 개선이 중심인가?'],
  },
  earnings_guidance_negative: {
    caseType: 'earnings_guidance_negative',
    caseLabelKo: '실적 부진·가이던스 하향',
    topLevel: 'short',
    description: '실적 miss, weak outlook, 가이던스 하향처럼 펀더멘털 하방을 직접 시사하는 기사다.',
    definition: 'headline/lead에서 숫자 악화 또는 guidance cut이 핵심 사건이면 이 유형이다.',
    valuePath: '추정치 하향 -> 멀티플 압축 -> 실적 기반 재평가 하락으로 이어진다.',
    includeSignals: ['missed estimates', 'misses estimates', 'lowered guidance', 'cuts guidance', 'weak outlook', 'below expectations'],
    excludeSignals: ['실적 기사지만 beat가 메인인 경우', '실적 발표 일정 공지만 있는 경우'],
    boundaryCase: '같은 실적 기사라도 본문에서 숫자보다 구조조정/자금조달이 더 중심이면 인접 유형을 재검토한다.',
    quickQuestions: ['가이던스 하향 또는 miss가 핵심인가?', '숫자 악화가 직접 가격 하방을 설명하는가?'],
  },
  analyst_upgrade_positive: {
    caseType: 'analyst_upgrade_positive',
    caseLabelKo: '애널리스트 상향·목표가 상향',
    topLevel: 'long',
    description: 'sell-side의 buy/outperform 의견 상향 또는 target raise가 중심인 기사다.',
    definition: '기사 주체가 회사 공시가 아니라 애널리스트 리포트이고, rating/target 상향이 핵심이면 이 유형이다.',
    valuePath: '외부 해석 변화 -> 수급 유입 -> 멀티플 re-rating 기대를 만든다.',
    includeSignals: ['upgrade', 'upgraded', 'raises price target', 'target raised', 'buy rating', 'outperform'],
    excludeSignals: ['회사 자체 실적/계약 뉴스', 'maintain만 있고 상향 근거가 약한 경우'],
    boundaryCase: '애널리스트가 회사 이벤트를 인용해도 중심 사건이 rating/target 변화면 이 유형으로 둔다.',
    quickQuestions: ['기사의 주체가 analyst firm인가?', 'rating 또는 target 상향이 제목에 드러나는가?'],
  },
  analyst_downgrade_negative: {
    caseType: 'analyst_downgrade_negative',
    caseLabelKo: '애널리스트 하향·목표가 하향',
    topLevel: 'short',
    description: 'sell-side의 downgrade, underweight, target cut이 중심인 기사다.',
    definition: '기사의 메인 메시지가 분석가의 하향 의견이면 이 유형이다.',
    valuePath: '외부 해석 악화 -> 수급 이탈 -> 멀티플 압박으로 연결된다.',
    includeSignals: ['downgrade', 'downgraded', 'cuts price target', 'target cut', 'price target cut', 'underweight', 'sell rating'],
    excludeSignals: ['회사 공시 중심 기사', '단순 유지 의견 기사'],
    boundaryCase: 'earnings miss를 인용해도 제목 중심이 analyst action이면 이 유형을 우선한다.',
    quickQuestions: ['downgrade 또는 target cut이 핵심인가?', '기사 주체가 회사보다 analyst인가?'],
  },
  contract_partnership_positive: {
    caseType: 'contract_partnership_positive',
    caseLabelKo: '대형 계약·제휴·수주',
    topLevel: 'long',
    description: '실질 경제 가치가 있는 계약, 공급 agreement, partnership, collaboration, grant를 다룬 기사다.',
    definition: 'headline/lead에서 계약 체결 또는 파트너십 성사 자체가 중심 사건이면 이 유형이다.',
    valuePath: '매출 가시성/전략적 외부 자원 유입 -> 가치 상방으로 연결된다.',
    includeSignals: ['contract award', 'wins contract', 'partnership', 'collaboration', 'license agreement', 'grant award', 'government contract'],
    excludeSignals: ['형식적 MOU', '단순 행사/홍보 협업', '희석성 financing이 더 중심인 기사'],
    boundaryCase: 'agreement라는 단어만으로 분류하지 않고 경제적 연결이 있는지 함께 본다.',
    quickQuestions: ['실질 경제 이벤트가 있는 계약인가?', '매출/전략가치 증가 경로가 분명한가?'],
  },
  product_growth_positive: {
    caseType: 'product_growth_positive',
    caseLabelKo: '제품·서비스 성장 기대',
    topLevel: 'long',
    description: '신제품 launch, capacity expansion, demand surge, 서비스 확장처럼 성장 기대를 다루는 기사다.',
    definition: '핵심 메시지가 상업화 확대, 수요 증가, 사업 확장이라면 이 유형이다.',
    valuePath: '성장 기대 -> 매출 레버리지 기대 -> re-rating으로 이어진다.',
    includeSignals: ['launch', 'product launch', 'new service', 'expansion', 'capacity expansion', 'strong demand', 'growth catalyst'],
    excludeSignals: ['단순 제품 소개 기사', 'conference appearance', 'generic marketing copy'],
    boundaryCase: '실제 사업 확장인지 홍보성 소개인지 구분이 필요하다.',
    quickQuestions: ['실제 매출/운영 확대가 보이는가?', 'headline이 성장 기대를 직접 설명하는가?'],
  },
  regulatory_clinical_positive: {
    caseType: 'regulatory_clinical_positive',
    caseLabelKo: '승인·임상 호재',
    topLevel: 'long',
    description: 'FDA approval, positive topline, NDA/BLA acceptance 같은 임상·규제 상방 기사다.',
    definition: '바이오/헬스케어 자산의 성공 가능성 확대가 메인 메시지면 이 유형이다.',
    valuePath: '개발 자산 성공 확률 상승 -> 상업화 기대 확대 -> 가치 재평가로 이어진다.',
    includeSignals: ['fda approval', 'positive topline', 'topline results', 'pivotal data', 'nda acceptance', 'bla acceptance'],
    excludeSignals: ['trial mention만 있고 결과 방향이 없는 경우', '임상 실패/보류 기사'],
    boundaryCase: '비(非)바이오 산업에서는 같은 단어가 나와도 오분류 가능성이 커서 맥락 확인이 필요하다.',
    quickQuestions: ['성공/승인/수용이 핵심인가?', '핵심 자산 가치 상승을 직접 시사하는가?'],
  },
  regulatory_clinical_negative: {
    caseType: 'regulatory_clinical_negative',
    caseLabelKo: '규제·임상 악재',
    topLevel: 'short',
    description: 'CRL, endpoint failure, trial setback, clinical hold 같은 임상·규제 하방 기사다.',
    definition: '핵심 자산의 성공 확률 하락이 메인 메시지면 이 유형이다.',
    valuePath: '개발 리스크 확대 -> 상업화 지연/실패 -> 가치 훼손으로 이어진다.',
    includeSignals: ['complete response letter', 'crl', 'failed to meet', 'clinical hold', 'fda rejection', 'missed endpoint'],
    excludeSignals: ['trial 성공 기사', '연구 개시/일반 업데이트'],
    boundaryCase: 'trial 관련 기사라도 결과가 positive면 long 유형으로 보내야 한다.',
    quickQuestions: ['핵심 endpoint 실패 또는 규제 setback인가?', '핵심 자산 가치 하락을 설명하는가?'],
  },
  financing_dilution_negative: {
    caseType: 'financing_dilution_negative',
    caseLabelKo: '희석성 자금조달',
    topLevel: 'short',
    description: 'public offering, private placement, warrants, convertibles처럼 주주 희석 가능성이 큰 기사다.',
    definition: '핵심 사건이 자본 조달이며 기존 주주 희석 위험이 직접 연결되면 이 유형이다.',
    valuePath: '희석 또는 자본비용 상승 우려 -> 주가 하방 압력으로 이어진다.',
    includeSignals: ['public offering', 'registered direct', 'private placement', 'warrant', 'convertible notes', 'secondary offering'],
    excludeSignals: ['비희석성 grant', '실질 계약/제휴 기사'],
    boundaryCase: '자금 조달 기사라도 non-dilutive 성격이면 다른 유형을 검토한다.',
    quickQuestions: ['주식/워런트/전환증권 발행이 핵심인가?', '희석 우려가 직접 드러나는가?'],
  },
  litigation_regulatory_negative: {
    caseType: 'litigation_regulatory_negative',
    caseLabelKo: '소송·조사·회계 리스크',
    topLevel: 'short',
    description: 'lawsuit, investigation, subpoena, fraud, restatement 같은 법률/신뢰 리스크 기사다.',
    definition: '메인 메시지가 규제·법률·회계 리스크 발생이면 이 유형이다.',
    valuePath: '불확실성 확대 -> 비용 증가 및 신뢰 훼손 -> 하방 압력으로 연결된다.',
    includeSignals: ['lawsuit', 'class action', 'investigation', 'sec probe', 'restatement', 'fraud', 'subpoena'],
    excludeSignals: ['리스크 해소 기사', '일반 법무 업데이트'],
    boundaryCase: '조사 종결/합의 완료처럼 리스크 해소면 이 유형으로 두지 않는다.',
    quickQuestions: ['법률/회계 리스크 자체가 메인인가?', '사업보다 조사/소송이 더 중심인가?'],
  },
  restructuring_distress_negative: {
    caseType: 'restructuring_distress_negative',
    caseLabelKo: '구조조정·생존성 악화',
    topLevel: 'short',
    description: 'bankruptcy, going concern, non-compliance, strategic alternatives, layoff 같은 생존성 기사다.',
    definition: '기업이 성장보다 생존 모드에 들어갔다는 신호가 중심이면 이 유형이다.',
    valuePath: '생존성 우려 확대 -> 할인율 상승 -> 가치 훼손으로 이어진다.',
    includeSignals: ['chapter 11', 'bankruptcy', 'going concern', 'delisting notice', 'non-compliance', 'strategic alternatives', 'layoffs'],
    excludeSignals: ['성장 투자 목적 조직 개편', '단순 효율화 코멘트'],
    boundaryCase: 'restructuring이라는 단어만으로 분류하지 않고 distress 맥락이 있는지 본다.',
    quickQuestions: ['핵심이 성장보다 생존인가?', '상장 유지/현금 유동성 우려가 중심인가?'],
  },
  mna_asset_value_positive: {
    caseType: 'mna_asset_value_positive',
    caseLabelKo: 'M&A·전략가치 재평가',
    topLevel: 'long',
    description: 'acquisition, merger, strategic investment, asset sale처럼 전략가치 재평가를 만드는 기사다.',
    definition: '자산/회사 가치가 거래 이벤트를 통해 재해석되는 경우 이 유형이다.',
    valuePath: '자산 가치 가시화 또는 전략적 프리미엄 기대 -> 재평가로 이어진다.',
    includeSignals: ['acquisition', 'merger', 'takeover', 'strategic investment', 'asset sale', 'buyout'],
    excludeSignals: ['형식적 검토 기사', '구조조정 distress가 더 중심인 기사'],
    boundaryCase: '매각/인수 기사라도 distress liquidation 맥락이면 short 유형을 우선 검토한다.',
    quickQuestions: ['거래 이벤트가 가치 재평가를 직접 만들고 있는가?', 'headline 중심이 M&A/전략투자인가?'],
  },
  macro_sector_readthrough: {
    caseType: 'macro_sector_readthrough',
    caseLabelKo: '매크로·섹터 read-through',
    topLevel: 'residual',
    description: '개별 회사 고유 이벤트보다 정책, 금리, 경기, 섹터 분위기 설명이 중심인 기사다.',
    definition: '같은 기사 구조를 여러 종목에 붙여도 의미가 통하면 이 유형으로 본다.',
    valuePath: '외부 환경 변화 -> 섹터/테마 read-through -> 개별 종목 재평가로 이어진다.',
    includeSignals: ['tariff', 'interest rates', 'fed', 'inflation', 'recession', 'sector weakness', 'economic slowdown', 'geopolitical'],
    excludeSignals: ['개별 회사 실적/계약/승인 뉴스', 'analyst action 기사'],
    boundaryCase: 'why is stock moving 기사라도 개별 원인이 뚜렷하면 해당 직접 유형으로 보내야 한다.',
    quickQuestions: ['개별 회사 사건보다 외부 환경이 중심인가?', '같은 문장이 여러 종목에 반복 적용되는가?'],
  },
  meaningless_others: {
    caseType: 'meaningless_others',
    caseLabelKo: '잡것들',
    topLevel: 'residual',
    description: 'listicle, generic commentary, low-information roundup, 홍보성 문구처럼 독립 유형으로 설명력이 약한 잔여 기사다.',
    definition: '반복성은 있어도 직접 경제 사건이 약하고, 별도 case로 올리기 어려운 row를 이 버킷에 둔다.',
    valuePath: '직접 가치 경로가 약하거나 불명확해서 residual로 남긴다.',
    includeSignals: ['most active stocks', 'stocks to buy', 'best stocks', 'wall street favorite', 'forecast', 'why this stock', 'generic roundup'],
    excludeSignals: ['실적, analyst action, 계약, 자금조달, 소송처럼 명확한 경제 사건 기사'],
    boundaryCase: '잔여 버킷은 휴지통이 아니라 후속 승격 후보 보관소다. 반복 패턴이 확인되면 독립 case로 분리할 수 있다.',
    quickQuestions: ['직접 경제 사건이 약한가?', '다른 독립 case로 분리할 설명력이 아직 부족한가?'],
  },
};

export function getModel2CaseDescription(caseType: string): CaseDescriptionWindowData {
  return MODEL2_CASE_DESCRIPTIONS[caseType] ?? MODEL2_CASE_DESCRIPTIONS.meaningless_others;
}