import { CaseDescriptionWindowData } from './types';

type CaseSeed = Omit<CaseDescriptionWindowData, 'caseType'>;

function toKeywordSignals(includeSignals: string[], excludeSignals: string[]): string[] {
  return [...includeSignals, ...excludeSignals.map(signal => `exclude:${signal}`)];
}

function toClassificationBasis(includeSignals: string[], excludeSignals: string[]): string {
  const includeText = includeSignals.length > 0 ? includeSignals.join(', ') : '명시 키워드 없음';
  const excludeText = excludeSignals.length > 0 ? excludeSignals.join(', ') : '제외 키워드 없음';
  return `title/body/publisher 텍스트에서 포함 신호(${includeText})를 먼저 찾고, 제외 신호(${excludeText})와 충돌하지 않을 때 이 유형으로 분류한다.`;
}

function buildCase(caseType: string, seed: CaseSeed): CaseDescriptionWindowData {
  const keywordSignals = seed.keywordSignals ?? toKeywordSignals(seed.includeSignals, seed.excludeSignals);
  const classificationBasis = seed.classificationBasis ?? toClassificationBasis(seed.includeSignals, seed.excludeSignals);
  return {
    caseType,
    keywordSignals,
    classificationBasis,
    ...seed,
  };
}

function aliasCase(caseType: string, base: CaseDescriptionWindowData, overrides?: Partial<CaseSeed>): CaseDescriptionWindowData {
  return {
    ...base,
    ...overrides,
    keywordSignals: overrides?.keywordSignals ?? base.keywordSignals,
    classificationBasis: overrides?.classificationBasis ?? base.classificationBasis,
    caseType,
  };
}

const TAXONOMY_V3_CASES: Record<string, CaseDescriptionWindowData> = {
  earnings_beat_raise_positive: buildCase('earnings_beat_raise_positive', {
    caseLabelKo: '실적 호조·가이던스 상향',
    topLevel: 'long',
    description: '실적 beat, strong results, guidance raise가 직접 원인인 기사다.',
    definition: 'headline과 lead에서 분기 숫자 개선이나 가이던스 상향이 사건 본체이면 이 유형이다.',
    valuePath: '추정치 상향과 멀티플 re-rating으로 이어진다.',
    includeSignals: ['beat estimates', 'raises guidance', 'better-than-expected', 'record revenue'],
    excludeSignals: ['earnings preview', 'earnings transcript', '실적 일정 안내'],
    boundaryCase: '실적 기사 안에 다른 재료가 같이 있어도 숫자 개선이 headline 중심이면 이 유형을 우선한다.',
    quickQuestions: ['실제 결과 기사인가?', 'beat 또는 raise가 제목 핵심인가?'],
  }),
  earnings_miss_cut_negative: buildCase('earnings_miss_cut_negative', {
    caseLabelKo: '실적 부진·가이던스 하향',
    topLevel: 'short',
    description: '실적 miss, weak outlook, guidance cut이 직접 원인인 기사다.',
    definition: 'headline과 lead에서 숫자 악화 또는 가이던스 하향이 사건 본체이면 이 유형이다.',
    valuePath: '추정치 하향과 valuation compression으로 이어진다.',
    includeSignals: ['misses estimates', 'cuts guidance', 'weak outlook', 'profit warning'],
    excludeSignals: ['preview', 'transcript', '단순 컨퍼런스 발언'],
    boundaryCase: '구조조정 기사 안에 실적 언급이 섞여 있어도 중심 사건이 miss/cut이 아니면 인접 short 유형을 본다.',
    quickQuestions: ['실제 결과 기사인가?', 'miss 또는 cut이 핵심인가?'],
  }),
  earnings_preview_watch: buildCase('earnings_preview_watch', {
    caseLabelKo: '실적 발표 전 기대 기사',
    topLevel: 'residual',
    description: '실적 발표 전 expectations, watch point, preview를 설명하는 기사다.',
    definition: '아직 결과가 나오지 않았고 기대 형성 단계라면 이 유형이다.',
    valuePath: '직접 이벤트가 아니라 기대 형성 단계라 residual로 둔다.',
    includeSignals: ['ahead of earnings', 'to report q1 results', 'wall street expects'],
    excludeSignals: ['beat estimates', 'misses estimates'],
    boundaryCase: 'preview 기사라도 실제 숫자 발표 이후면 result 유형으로 보내야 한다.',
    quickQuestions: ['실제 결과 전 기사인가?', '핵심이 기대치 안내인가?'],
  }),
  earnings_transcript_snapshot: buildCase('earnings_transcript_snapshot', {
    caseLabelKo: '실적 transcript·snapshot',
    topLevel: 'residual',
    description: 'earnings call transcript, snapshot, highlights 같은 후행 정리 기사다.',
    definition: '새 사건보다 call 전사본·요약 정리 성격이 강하면 이 유형이다.',
    valuePath: '원인 기사라기보다 정리 기사라서 직접 case로 보지 않는다.',
    includeSignals: ['earnings call transcript', 'earnings snapshot', 'conference call transcript'],
    excludeSignals: ['beat estimates', 'guidance cut'],
    boundaryCase: '요약 기사 안에 방향이 보여도 실제 사건 source가 아니라면 transcript 쪽을 우선한다.',
    quickQuestions: ['전사본/스냅샷인가?', '새 사건보다 요약 정리인가?'],
  }),
  analyst_upgrade_positive: buildCase('analyst_upgrade_positive', {
    caseLabelKo: '애널리스트 상향·커버리지 개시',
    topLevel: 'long',
    description: 'buy/outperform, coverage initiation, target raise가 메인인 기사다.',
    definition: '회사 이벤트보다 sell-side formal action이 headline 중심이면 이 유형이다.',
    valuePath: '외부 해석 상향이 short-term flow와 re-rating 기대를 만든다.',
    includeSignals: ['initiates coverage', 'outperform', 'raises price target', 'buy rating'],
    excludeSignals: ['target cut', 'downgraded'],
    boundaryCase: 'analyst가 회사 이벤트를 인용해도 rating/target 변화가 headline이면 이 유형이다.',
    quickQuestions: ['formal analyst action인가?', '상향 메시지인가?'],
  }),
  analyst_downgrade_negative: buildCase('analyst_downgrade_negative', {
    caseLabelKo: '애널리스트 하향·목표가 하향',
    topLevel: 'short',
    description: 'downgrade, underperform, target cut이 메인인 기사다.',
    definition: '회사 공시보다 sell-side 하향 action이 headline 중심이면 이 유형이다.',
    valuePath: '외부 해석 악화가 기대치 조정과 수급 이탈로 이어진다.',
    includeSignals: ['downgraded', 'underperform', 'target cut', 'underweight'],
    excludeSignals: ['initiates coverage', 'raises price target'],
    boundaryCase: 'earnings miss를 인용해도 중심이 analyst action이면 이 유형을 우선한다.',
    quickQuestions: ['formal downgrade 또는 target cut인가?', '기사 주체가 analyst인가?'],
  }),
  analyst_note_amplification_positive: buildCase('analyst_note_amplification_positive', {
    caseLabelKo: '애널리스트 코멘트 증폭·긍정',
    topLevel: 'long',
    description: 'formal upgrade는 아니지만 bullish note나 single-line mention이 해설 중심인 기사다.',
    definition: '정식 rating 변경 없이 analyst mention이 가격 설명의 핵심이면 이 유형이다.',
    valuePath: '짧은 note 증폭이 short-term sentiment와 수급을 밀어 올린다.',
    includeSignals: ['analyst says', 'bofa says', 'bullish note', 'analyst comment helped'],
    excludeSignals: ['formal upgrade', 'contract award'],
    boundaryCase: '정식 rating/target 변경이 있으면 formal analyst action으로 보낸다.',
    quickQuestions: ['rating action보다 note 증폭인가?', '긍정 논지인가?'],
  }),
  analyst_note_amplification_negative: buildCase('analyst_note_amplification_negative', {
    caseLabelKo: '애널리스트 코멘트 증폭·부정',
    topLevel: 'short',
    description: 'formal downgrade는 아니지만 cautious note나 skeptical commentary가 해설 중심인 기사다.',
    definition: '정식 하향 없이 analyst warning이 가격 설명 중심이면 이 유형이다.',
    valuePath: '보수적 note가 기대치와 단기 flow를 꺾는다.',
    includeSignals: ['analyst warns', 'cautious note', 'bearish note', 'skeptical analyst'],
    excludeSignals: ['formal downgrade', 'earnings miss'],
    boundaryCase: 'target cut이나 downgrade가 있으면 formal analyst short 유형을 우선한다.',
    quickQuestions: ['정식 하향보다 note 증폭인가?', '부정 논지인가?'],
  }),
  government_contract_award_positive: buildCase('government_contract_award_positive', {
    caseLabelKo: '정부·대형 계약 수주',
    topLevel: 'long',
    description: 'prime contractor, definitive contract, government award가 직접 재료인 기사다.',
    definition: '실제 수주·backlog 확대가 headline 핵심이면 이 유형이다.',
    valuePath: '매출 가시성과 backlog 확대를 직접 시사한다.',
    includeSignals: ['contract award', 'wins contract', 'prime contractor', 'government contract'],
    excludeSignals: ['generic partnership', 'grant commentary'],
    boundaryCase: '실질 수주가 아니라 협력 관계 소개면 partnership 쪽을 검토한다.',
    quickQuestions: ['실제 수주가 headline 핵심인가?', '경제적 규모가 있는 계약인가?'],
  }),
  partnership_license_positive: buildCase('partnership_license_positive', {
    caseLabelKo: '제휴·라이선스·협업',
    topLevel: 'long',
    description: 'partnership, collaboration, licensing deal이 직접 재료인 기사다.',
    definition: '실질 협업 구조나 license agreement가 핵심이면 이 유형이다.',
    valuePath: '외부 자원 결합과 channel 확대가 가치 상승 경로를 만든다.',
    includeSignals: ['partnership', 'collaboration', 'license agreement', 'licensing deal'],
    excludeSignals: ['offering', 'lawsuit'],
    boundaryCase: 'headline에 agreement가 있어도 경제적 연결이 약하면 residual로 보낼 수 있다.',
    quickQuestions: ['경제적 제휴인가?', '실질 협업이 headline 중심인가?'],
  }),
  commercial_launch_expansion_positive: buildCase('commercial_launch_expansion_positive', {
    caseLabelKo: '출시·상업화·확장',
    topLevel: 'long',
    description: 'launch, rollout, expansion, commercialization이 직접 재료인 기사다.',
    definition: '제품/서비스 상업화 확대가 사건 본체이면 이 유형이다.',
    valuePath: '채택 확대와 매출 성장 기대를 만든다.',
    includeSignals: ['launches', 'launch', 'expands', 'commercial launch'],
    excludeSignals: ['event promotion', 'generic preview'],
    boundaryCase: '단순 제품 소개나 마케팅 copy면 residual이나 feature 쪽을 본다.',
    quickQuestions: ['실제 상업화/확장 이벤트인가?', '매출 연결이 보이는가?'],
  }),
  demand_backlog_positive: buildCase('demand_backlog_positive', {
    caseLabelKo: '수요 급증·백로그 확대',
    topLevel: 'long',
    description: 'strong demand, bookings, backlog growth가 직접 원인인 기사다.',
    definition: 'headline과 lead에서 수요·주문 가시성 확대가 핵심이면 이 유형이다.',
    valuePath: '매출 지속성과 operating leverage 기대를 높인다.',
    includeSignals: ['strong demand', 'demand surge', 'backlog', 'bookings growth'],
    excludeSignals: ['macro demand commentary', 'general feature'],
    boundaryCase: '직접 backlog 언급이 없고 peer나 섹터 read-through면 indirect 쪽을 본다.',
    quickQuestions: ['수요/백로그가 직접 언급되는가?', '회사 고유 사건인가?'],
  }),
  customer_adoption_positive: buildCase('customer_adoption_positive', {
    caseLabelKo: '고객 채택·대형 고객 확보',
    topLevel: 'long',
    description: 'major customer win, adoption, deployment 확대가 직접 재료인 기사다.',
    definition: '신규 고객 확보나 deployment가 headline 핵심이면 이 유형이다.',
    valuePath: '고객 기반 확대가 매출과 credibility 상승으로 이어진다.',
    includeSignals: ['customer win', 'adoption', 'selected by', 'deployment'],
    excludeSignals: ['generic partnership', 'watchlist article'],
    boundaryCase: '수주가 정부·방산 중심이면 contract award 쪽을 우선 검토한다.',
    quickQuestions: ['고객 채택이 headline 중심인가?', '매출 연결이 분명한가?'],
  }),
  shareholder_return_positive: buildCase('shareholder_return_positive', {
    caseLabelKo: '자사주 매입·주주환원',
    topLevel: 'long',
    description: 'share repurchase, buyback, dividend hike가 직접 재료인 기사다.',
    definition: '자본배분과 환원정책 강화가 사건 본체이면 이 유형이다.',
    valuePath: 'share count 감소와 capital return 기대가 valuation support를 만든다.',
    includeSignals: ['share repurchase', 'buyback', 'repurchase program', 'increases dividend'],
    excludeSignals: ['capital raise', 'reverse split'],
    boundaryCase: '대규모 debt-funded action이라도 headline 중심이 환원정책이면 이 유형을 유지한다.',
    quickQuestions: ['주주환원 강화가 핵심인가?', '희석이 아니라 환원인가?'],
  }),
  mna_strategic_asset_positive: buildCase('mna_strategic_asset_positive', {
    caseLabelKo: 'M&A·전략자산 거래',
    topLevel: 'long',
    description: 'acquisition, merger, buyout, strategic investment가 직접 재료인 기사다.',
    definition: '자산·회사 거래가 가치 재평가의 핵심 통로이면 이 유형이다.',
    valuePath: '전략 자산 가치 가시화와 premium 기대를 만든다.',
    includeSignals: ['acquisition', 'merger', 'buyout', 'strategic investment'],
    excludeSignals: ['distress sale', 'capital raise'],
    boundaryCase: '생존형 매각이나 채무압박 해소가 더 중심이면 distress 쪽을 본다.',
    quickQuestions: ['자산/회사 거래가 headline 핵심인가?', '전략가치 재평가가 중심인가?'],
  }),
  regulatory_clinical_positive: buildCase('regulatory_clinical_positive', {
    caseLabelKo: '승인·임상 호재',
    topLevel: 'long',
    description: 'FDA approval, positive topline, NDA/BLA acceptance가 직접 재료인 기사다.',
    definition: '핵심 자산 성공 확률 상승이 headline 중심이면 이 유형이다.',
    valuePath: '상업화 기대와 asset value re-rating을 만든다.',
    includeSignals: ['fda approval', 'positive topline', 'nda acceptance', 'pivotal data'],
    excludeSignals: ['clinical hold', 'failed endpoint'],
    boundaryCase: '결과가 mixed여도 headline이 approval/success면 positive 임상 유형을 유지한다.',
    quickQuestions: ['성공/승인이 headline 중심인가?', '핵심 자산 가치 상승을 설명하는가?'],
  }),
  regulatory_clinical_negative: buildCase('regulatory_clinical_negative', {
    caseLabelKo: '규제·임상 악재',
    topLevel: 'short',
    description: 'CRL, endpoint failure, clinical hold, rejection이 직접 재료인 기사다.',
    definition: '핵심 자산 성공 확률 하락이 headline 중심이면 이 유형이다.',
    valuePath: '상업화 지연·실패로 핵심 asset value를 깎는다.',
    includeSignals: ['complete response letter', 'clinical hold', 'failed to meet', 'fda rejection'],
    excludeSignals: ['positive topline', 'approval'],
    boundaryCase: '규제 기사라도 정책 프레임워크 일반론이면 policy read-through 쪽을 본다.',
    quickQuestions: ['실패/보류가 중심인가?', '핵심 자산 가치 하락을 설명하는가?'],
  }),
  financing_dilution_negative: buildCase('financing_dilution_negative', {
    caseLabelKo: '희석성 자금조달',
    topLevel: 'short',
    description: 'public offering, private placement, warrants, convertibles가 직접 재료인 기사다.',
    definition: '자본 조달 자체가 headline 중심이고 기존 주주 희석 우려가 분명하면 이 유형이다.',
    valuePath: '희석과 자본비용 상승 우려가 주가 하방으로 이어진다.',
    includeSignals: ['public offering', 'private placement', 'warrants', 'convertible notes'],
    excludeSignals: ['grant award', 'non-dilutive funding'],
    boundaryCase: '조달 기사라도 non-dilutive 성격이면 이 유형에 넣지 않는다.',
    quickQuestions: ['조달 자체가 headline 핵심인가?', '희석 우려가 직접적인가?'],
  }),
  capital_structure_stress_negative: buildCase('capital_structure_stress_negative', {
    caseLabelKo: '거래정지·역분할·상장유지 스트레스',
    topLevel: 'short',
    description: 'trading halt, reverse split, compliance pressure, authorized shares가 직접 재료인 기사다.',
    definition: '사업 사건보다 시장구조·상장유지 스트레스가 중심이면 이 유형이다.',
    valuePath: '유동성·희석·상장유지 우려가 주가에 직접 할인으로 반영된다.',
    includeSignals: ['trading halt', 'reverse stock split', 'minimum bid', 'authorized shares'],
    excludeSignals: ['ipo debut', 'ordinary listing'],
    boundaryCase: 'reverse split과 public offering이 같이 있으면 headline 중심 재료를 먼저 본다.',
    quickQuestions: ['사업보다 자본구조 스트레스가 중심인가?', '상장유지 이슈가 있는가?'],
  }),
  litigation_regulatory_negative: buildCase('litigation_regulatory_negative', {
    caseLabelKo: '소송·조사·회계 리스크',
    topLevel: 'short',
    description: 'lawsuit, investigation, subpoena, fraud, restatement가 직접 재료인 기사다.',
    definition: '법률·회계·신뢰 리스크가 headline 중심이면 이 유형이다.',
    valuePath: '비용 증가와 신뢰 훼손이 valuation discount를 만든다.',
    includeSignals: ['lawsuit', 'investigation', 'subpoena', 'restatement'],
    excludeSignals: ['settlement removes risk', 'approval'],
    boundaryCase: '리스크 해소·합의 완료 기사면 이 유형에 그대로 두지 않는다.',
    quickQuestions: ['조사/소송이 핵심인가?', '사업보다 법률 리스크가 중심인가?'],
  }),
  restructuring_distress_negative: buildCase('restructuring_distress_negative', {
    caseLabelKo: '구조조정·생존성 악화',
    topLevel: 'short',
    description: 'bankruptcy, going concern, layoffs, strategic alternatives가 직접 재료인 기사다.',
    definition: '성장보다 생존 모드 전환이 headline 중심이면 이 유형이다.',
    valuePath: '생존성 우려와 사업 지속성 discount를 만든다.',
    includeSignals: ['chapter 11', 'bankruptcy', 'going concern', 'layoffs'],
    excludeSignals: ['growth reorg', 'ordinary cost cuts'],
    boundaryCase: '단순 효율화 코멘트나 성장투자형 조직개편은 이 유형에 넣지 않는다.',
    quickQuestions: ['성장보다 생존이 핵심인가?', '유동성 또는 상장유지 우려가 있는가?'],
  }),
  management_governance_positive: buildCase('management_governance_positive', {
    caseLabelKo: '경영진 보강·거버넌스 개선',
    topLevel: 'long',
    description: 'experienced CEO/CFO 영입, board refresh, governance agreement가 직접 재료인 기사다.',
    definition: '운영 신뢰 회복이나 실행력 개선이 headline 중심이면 이 유형이다.',
    valuePath: '리더십 개선 기대가 valuation support를 만든다.',
    includeSignals: ['appoints new ceo', 'board refresh', 'governance agreement', 'new leadership'],
    excludeSignals: ['executive departure', 'probe'],
    boundaryCase: 'planned succession이라도 긍정 재평가가 메인 아니면 residual로 둘 수 있다.',
    quickQuestions: ['경영 보강이 긍정 이벤트인가?', '거버넌스 개선이 중심인가?'],
  }),
  management_governance_negative: buildCase('management_governance_negative', {
    caseLabelKo: '경영진 이탈·거버넌스 충격',
    topLevel: 'short',
    description: 'CEO/CFO resignation, board dispute, governance breakdown이 직접 재료인 기사다.',
    definition: '리더십 공백이나 통제 약화가 headline 중심이면 이 유형이다.',
    valuePath: '실행력 저하와 신뢰 악화 우려를 만든다.',
    includeSignals: ['ceo resigns', 'cfo resigns', 'board dispute', 'executive departs'],
    excludeSignals: ['planned succession', 'new ceo appointed'],
    boundaryCase: '새 리더 선임이 동반돼도 headline 중심이 이탈이면 negative governance를 우선한다.',
    quickQuestions: ['경영 공백/혼란이 핵심인가?', '거버넌스 충격이 headline인가?'],
  }),
  policy_regulatory_tailwind_positive: buildCase('policy_regulatory_tailwind_positive', {
    caseLabelKo: '정책·법안 수혜 read-through',
    topLevel: 'long',
    description: '법안, 정책, 규제 프레임워크 변화가 사업모델에 우호적으로 작용하는 기사다.',
    definition: '회사 직접 공시가 아니라 외부 정책 변화가 수혜 논리의 핵심이면 이 유형이다.',
    valuePath: '규제완화나 시장확대 기대가 TAM 확장 논리로 이어진다.',
    includeSignals: ['policy support', 'regulatory clarity', 'bill boosts', 'tailwind from policy'],
    excludeSignals: ['company contract', 'formal approval'],
    boundaryCase: '회사가 직접 허가를 받은 것이면 regulatory positive로 보내고, 외부 법안 수혜면 이 유형이다.',
    quickQuestions: ['직접 공시가 아니라 정책 수혜 read-through인가?', '외부 프레임 변화가 핵심인가?'],
  }),
  policy_regulatory_headwind_negative: buildCase('policy_regulatory_headwind_negative', {
    caseLabelKo: '정책·법안 역풍 read-through',
    topLevel: 'short',
    description: '법안, 규제, 정책 프레임워크 변화가 사업모델에 역풍을 주는 기사다.',
    definition: '회사 직접 악재보다 외부 정책 변화가 약세 논리의 핵심이면 이 유형이다.',
    valuePath: '규제 강화·수익경로 제한 우려가 valuation discount를 만든다.',
    includeSignals: ['bill', 'act', 'ban', 'policy risk', 'regulatory framework'],
    excludeSignals: ['fda rejection', 'lawsuit'],
    boundaryCase: '개별 회사 규제 실패가 아니라 sector-wide framework 변화일 때 이 유형을 쓴다.',
    quickQuestions: ['정책 역풍이 핵심인가?', '개별 회사 공시보다 framework 변화가 중심인가?'],
  }),
  peer_readthrough_positive: buildCase('peer_readthrough_positive', {
    caseLabelKo: 'peer 호조 read-through',
    topLevel: 'long',
    description: 'peer strong earnings, peer validation, sector leader strength가 번져오는 기사다.',
    definition: '타사 호조가 현재 ticker 재평가 논리의 중심이면 이 유형이다.',
    valuePath: 'peer 실적·수요 신호가 동종 멀티플 상승으로 번진다.',
    includeSignals: ['peer results', 'peer strength', 'sector leader', 'read-through'],
    excludeSignals: ['same company earnings', 'macro only'],
    boundaryCase: '자사 실적 기사면 direct earnings, 타사 검증이면 peer read-through로 나눈다.',
    quickQuestions: ['타사 호조가 이 종목 논리의 핵심인가?', '동종 밸류에이션 전이가 핵심인가?'],
  }),
  peer_competition_negative: buildCase('peer_competition_negative', {
    caseLabelKo: 'peer 투자·경쟁 심화 read-through',
    topLevel: 'short',
    description: 'rival launch, peer capex, substitute threat가 약세 이유인 기사다.',
    definition: '경쟁사 행동이 현재 ticker 약세 논리의 중심이면 이 유형이다.',
    valuePath: '경쟁 심화와 share loss 우려가 valuation 압박으로 이어진다.',
    includeSignals: ['rival', 'competitor', 'investment push', 'competitive pressure'],
    excludeSignals: ['same company launch', 'macro risk-off'],
    boundaryCase: '단순 sector weakness가 아니라 특정 경쟁사 행동이 보여야 이 유형을 쓴다.',
    quickQuestions: ['경쟁사 행동이 약세 이유의 중심인가?', 'share-loss 우려가 핵심인가?'],
  }),
  supply_chain_tailwind_positive: buildCase('supply_chain_tailwind_positive', {
    caseLabelKo: '공급망 완화·원가 개선 read-through',
    topLevel: 'long',
    description: 'input cost easing, supply normalization, sourcing improvement가 핵심인 기사다.',
    definition: '회사 직접 공시가 아니라 외부 공급망 개선이 긍정 논리 중심이면 이 유형이다.',
    valuePath: '원가 하락과 생산 정상화가 margin upside로 이어진다.',
    includeSignals: ['supply chain easing', 'input costs fall', 'sourcing improves', 'cost relief'],
    excludeSignals: ['company contract', 'generic macro'],
    boundaryCase: '직접 계약/고객 확보가 아니라 외부 원가 환경 개선일 때 이 유형을 쓴다.',
    quickQuestions: ['공급망 개선이 핵심 논리인가?', 'margin 개선 read-through인가?'],
  }),
  supply_chain_headwind_negative: buildCase('supply_chain_headwind_negative', {
    caseLabelKo: '공급망 차질·원가 압박 read-through',
    topLevel: 'short',
    description: 'tariff exposure, rare earth sourcing, shortage, cost inflation이 핵심인 기사다.',
    definition: '회사 직접 악재보다 외부 공급망·원가 압박이 약세 논리 중심이면 이 유형이다.',
    valuePath: '원가 상승과 생산 차질이 margin 압박으로 이어진다.',
    includeSignals: ['tariff exposure', 'rare earth', 'shortage', 'cost inflation'],
    excludeSignals: ['macro index move', 'direct lawsuit'],
    boundaryCase: '정책 법안 자체가 headline이면 policy headwind, 소재·부품 제약이면 supply-chain headwind다.',
    quickQuestions: ['공급망/원가 압박이 중심인가?', 'margin 악화 read-through인가?'],
  }),
  valuation_narrative_positive: buildCase('valuation_narrative_positive', {
    caseLabelKo: '밸류에이션 discount 해소 narrative',
    topLevel: 'long',
    description: 'undervalued, discount, rerating potential이 핵심인 기사다.',
    definition: '직접 사건보다 저평가 해소 논리가 headline 중심이면 이 유형이다.',
    valuePath: 'multiple expansion 기대가 주가 상방 논리를 만든다.',
    includeSignals: ['undervalued', 'discount', 'catch-up', 'rerating potential'],
    excludeSignals: ['best stock list', 'formal analyst upgrade'],
    boundaryCase: 'generic buy article가 아니라 valuation mispricing 논리가 중심이어야 한다.',
    quickQuestions: ['저평가 해소 narrative가 중심인가?', '직접 이벤트보다 valuation 논리가 강한가?'],
  }),
  valuation_narrative_negative: buildCase('valuation_narrative_negative', {
    caseLabelKo: '밸류에이션 부담·multiple compression narrative',
    topLevel: 'short',
    description: 'too expensive, stretched valuation, multiple compression 우려가 핵심인 기사다.',
    definition: '펀더멘털 직접 악재보다 valuation 부담 논리가 headline 중심이면 이 유형이다.',
    valuePath: '추격 매수 둔화와 de-rating 우려를 만든다.',
    includeSignals: ['too expensive', 'stretched valuation', 'multiple compression', 'overvalued'],
    excludeSignals: ['formal downgrade', 'earnings miss'],
    boundaryCase: '정식 analyst cut이 있으면 analyst short, valuation 논평만 있으면 이 유형이다.',
    quickQuestions: ['valuation 부담이 중심인가?', '직접 이벤트보다 가격이 비싸다는 논리가 중심인가?'],
  }),
  positioning_flow_positive: buildCase('positioning_flow_positive', {
    caseLabelKo: '숏커버·포지셔닝 언와인드·매수 유입',
    topLevel: 'long',
    description: 'short squeeze, fund buying, covering이 상승 이유인 기사다.',
    definition: '사업 이벤트보다 positioning과 flow가 핵심이면 이 유형이다.',
    valuePath: '기계적 수급 유입이 가격 상승을 가속한다.',
    includeSignals: ['short squeeze', 'fund buying', 'position established', 'covering'],
    excludeSignals: ['buyback', 'customer adoption'],
    boundaryCase: '내부자 매수처럼 ownership change가 기사 본체면 이 유형과 information-flow 경계를 같이 본다.',
    quickQuestions: ['사업 사건보다 flow가 핵심인가?', '수급 유입이 headline 중심인가?'],
  }),
  positioning_flow_negative: buildCase('positioning_flow_negative', {
    caseLabelKo: '차익실현·디그로싱·매도 수급',
    topLevel: 'short',
    description: 'profit-taking, de-grossing, fund selling이 하락 이유인 기사다.',
    definition: '사업 악재보다 flow unwind가 headline 중심이면 이 유형이다.',
    valuePath: '포지셔닝 축소가 단기 가격 하방을 만든다.',
    includeSignals: ['profit-taking', 'taking profits', 'de-grossing', 'fund selling'],
    excludeSignals: ['earnings miss', 'policy risk'],
    boundaryCase: 'business deterioration보다 flow unwind 설명이 중심이어야 이 유형을 쓴다.',
    quickQuestions: ['사업 악재보다 flow unwind가 중심인가?', '차익실현 설명이 headline인가?'],
  }),
  media_amplification_positive: buildCase('media_amplification_positive', {
    caseLabelKo: 'top mover·헤드라인 증폭·상승 해설',
    topLevel: 'long',
    description: 'top mover, biggest gainer, shares jumped because 같은 상승 해설 기사다.',
    definition: '이미 오른 뒤 이유를 덧붙이는 explainer 구조가 핵심이면 이 유형이다.',
    valuePath: '노출 증폭과 headline cascade가 추가 관심을 만든다.',
    includeSignals: ['top mover', 'biggest gainer', 'surging today', 'soaring today'],
    excludeSignals: ['formal upgrade', 'contract award'],
    boundaryCase: '정식 analyst action이 중심이면 analyst case, 이미 오른 뒤 해설이면 media amplification이다.',
    quickQuestions: ['이미 오른 뒤 해설 기사인가?', '노출 증폭이 핵심인가?'],
  }),
  media_amplification_negative: buildCase('media_amplification_negative', {
    caseLabelKo: 'top mover·헤드라인 증폭·하락 해설',
    topLevel: 'short',
    description: 'why stock is falling, tumbles, sell-off 같은 하락 해설 기사다.',
    definition: '이미 내린 뒤 약세 이유를 묶는 explainer 구조가 핵심이면 이 유형이다.',
    valuePath: 'headline cascade가 공포와 추가 매도를 증폭한다.',
    includeSignals: ['trading lower today', 'tumbles', 'sell-off', 'plunges'],
    excludeSignals: ['formal downgrade', 'public offering'],
    boundaryCase: '직접 하방 사건이 headline 중심이면 direct short 유형을 우선하고, 사후 해설 구조면 이 유형을 쓴다.',
    quickQuestions: ['이미 내린 뒤 해설 기사인가?', 'headline cascade가 중심인가?'],
  }),
  macro_market_commentary: buildCase('macro_market_commentary', {
    caseLabelKo: '매크로·시장 코멘터리',
    topLevel: 'residual',
    description: '금리, Fed, 인플레이션, 지수 움직임처럼 광범위한 시장 설명 기사다.',
    definition: '개별 회사 고유 사건보다 시장 전반 설명이 중심이면 이 유형이다.',
    valuePath: '외부 환경 read-through를 다루지만 개별 기업 분류력은 낮다.',
    includeSignals: ['stock market today', 'fed', 'inflation', 'nasdaq', 's&p 500'],
    excludeSignals: ['single-company event', 'peer competition'],
    boundaryCase: '특정 정책 프레임 변화가 핵심이면 policy read-through로 세분화한다.',
    quickQuestions: ['여러 종목 공통 설명인가?', '개별 회사 사건보다 시장 설명인가?'],
  }),
  market_movers_roundup: buildCase('market_movers_roundup', {
    caseLabelKo: '멀티종목 movers·watchlist 기사',
    topLevel: 'residual',
    description: '여러 종목을 묶어 radar, movers, top stocks로 나열하는 기사다.',
    definition: '개별 사건보다 스크리너·roundup 구조가 중심이면 이 유형이다.',
    valuePath: '개별 가격 원인보다 요약·큐레이션 성격이 강하다.',
    includeSignals: ['other big stocks moving', 'investors\' radars', 'most active stocks', 'top stocks'],
    excludeSignals: ['single-ticker explainer', 'direct event'],
    boundaryCase: '한 종목 집중 설명이 아니라 다종목 나열이면 이 유형으로 둔다.',
    quickQuestions: ['멀티종목 roundup인가?', '요약·레이더 기사인가?'],
  }),
  ipo_listing_event: buildCase('ipo_listing_event', {
    caseLabelKo: 'IPO·상장 이벤트',
    topLevel: 'residual',
    description: 'IPO, direct listing, debut, goes public가 핵심인 기사다.',
    definition: '상장 자체가 사건 본체이면 이 유형이다.',
    valuePath: '시장 접근·유동성 이벤트지만 방향성은 case-by-case다.',
    includeSignals: ['goes public', 'ipo', 'direct listing', 'debut'],
    excludeSignals: ['trading halt', 'reverse split'],
    boundaryCase: '상장 후 reverse split이나 halt 기사면 capital-structure stress로 보낸다.',
    quickQuestions: ['상장 자체가 headline 핵심인가?', 'listing/debut 기사인가?'],
  }),
  generic_feature_commentary: buildCase('generic_feature_commentary', {
    caseLabelKo: 'feature·투자아이디어 해설',
    topLevel: 'residual',
    description: 'deep dive, is it a buy, worth buying, storytelling 성격의 feature 기사다.',
    definition: '직접 사건보다 opinion·해설 구조가 중심이면 이 유형이다.',
    valuePath: '직접 catalyst보다 해석 레이어에 가까워 residual로 둔다.',
    includeSignals: ['is it a buy', 'worth buying', 'deep dive', 'feature'],
    excludeSignals: ['formal analyst action', 'earnings beat'],
    boundaryCase: 'valuation mispricing 논리가 분명하면 valuation narrative로 승격하고, 아니면 feature로 둔다.',
    quickQuestions: ['직접 사건보다 feature/opinion인가?', '새 catalyst보다 해설 비중이 큰가?'],
  }),
  meaningless_others: buildCase('meaningless_others', {
    caseLabelKo: '잡것들',
    topLevel: 'residual',
    description: '독립 유형으로 재현 가능하게 설명하기 어려운 저정보 residual 기사다.',
    definition: '반복 패턴이 약하거나 직접 가치 경로가 불명확한 row를 임시로 이 버킷에 둔다.',
    valuePath: '직접 가격 설명력이 약하거나 아직 분리 기준이 부족하다.',
    includeSignals: ['generic promotion', 'ambiguous article', '저정보 recap'],
    excludeSignals: ['실적, analyst, 계약, 정책, peer, valuation, flow처럼 독립 설명이 가능한 기사'],
    boundaryCase: '휴지통이 아니라 후속 승격 후보 보관소다. 반복 패턴이 보이면 독립 case로 빼야 한다.',
    quickQuestions: ['독립 유형으로 올릴 만큼 반복 패턴이 약한가?', '직접 가치 경로가 불명확한가?'],
  }),
};

const LEGACY_COMPAT_CASES: Record<string, CaseDescriptionWindowData> = {
  earnings_guidance_positive: aliasCase('earnings_guidance_positive', TAXONOMY_V3_CASES.earnings_beat_raise_positive, {
    caseLabelKo: '실적 호조·가이던스 상향',
    description: 'legacy broad bucket이다. taxonomy v3에서는 earnings_beat_raise_positive로 세분화했다.',
  }),
  earnings_guidance_negative: aliasCase('earnings_guidance_negative', TAXONOMY_V3_CASES.earnings_miss_cut_negative, {
    caseLabelKo: '실적 부진·가이던스 하향',
    description: 'legacy broad bucket이다. taxonomy v3에서는 earnings_miss_cut_negative로 세분화했다.',
  }),
  contract_partnership_positive: buildCase('contract_partnership_positive', {
    caseLabelKo: '대형 계약·제휴·수주',
    topLevel: 'long',
    description: 'legacy broad bucket이다. taxonomy v3에서는 정부 계약과 partnership/license를 분리했다.',
    definition: '예전 run에서 계약 수주와 협업 기사 전반을 묶어 두던 상위 유형이다.',
    valuePath: '매출 가시성 또는 전략적 외부 자원 유입 기대를 만든다.',
    includeSignals: ['contract award', 'wins contract', 'partnership', 'collaboration'],
    excludeSignals: ['형식적 MOU', 'offering', 'lawsuit'],
    boundaryCase: '새 run에서는 government_contract_award_positive와 partnership_license_positive로 나눠서 본다.',
    quickQuestions: ['old run broad bucket인가?', '새 run에서는 더 세분화됐는가?'],
  }),
  product_growth_positive: aliasCase('product_growth_positive', TAXONOMY_V3_CASES.commercial_launch_expansion_positive, {
    caseLabelKo: '제품·서비스 성장 기대',
    description: 'legacy broad bucket이다. taxonomy v3에서는 launch/expansion, demand/backlog, customer adoption을 분리했다.',
  }),
  mna_asset_value_positive: aliasCase('mna_asset_value_positive', TAXONOMY_V3_CASES.mna_strategic_asset_positive, {
    caseLabelKo: 'M&A·전략가치 재평가',
    description: 'legacy broad bucket이다. taxonomy v3에서는 mna_strategic_asset_positive로 반영했다.',
  }),
  macro_sector_readthrough: buildCase('macro_sector_readthrough', {
    caseLabelKo: '매크로·섹터 read-through',
    topLevel: 'residual',
    description: 'legacy broad residual bucket이다. taxonomy v3에서는 policy, peer, supply-chain, valuation, media, macro commentary를 분리했다.',
    definition: '예전 run에서 외부 환경·해설 기사를 넓게 묶어 두던 상위 유형이다.',
    valuePath: '외부 환경 변화가 개별 종목에 read-through된다는 점은 맞지만, 분류력이 너무 넓었다.',
    includeSignals: ['tariff', 'fed', 'inflation', 'sector weakness', 'why stock moved'],
    excludeSignals: ['직접 실적/계약/임상 기사'],
    boundaryCase: '새 run에서는 policy_regulatory, peer, supply_chain, media_amplification, macro_market_commentary 등으로 나눠 읽어야 한다.',
    quickQuestions: ['old broad residual bucket인가?', '새 taxonomy에서는 더 구체적인 원인으로 나눌 수 있는가?'],
  }),
};

export const MODEL2_CASE_DESCRIPTIONS: Record<string, CaseDescriptionWindowData> = {
  ...TAXONOMY_V3_CASES,
  ...LEGACY_COMPAT_CASES,
};

export function getModel2CaseDescription(caseType: string): CaseDescriptionWindowData {
  return MODEL2_CASE_DESCRIPTIONS[caseType] ?? MODEL2_CASE_DESCRIPTIONS.meaningless_others;
}